// Code generated by lark_sdk_gen. DO NOT EDIT.
/**
 * Copyright 2022 chyroc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package lark

import (
	"context"
)

// CreateBitableApp 在指定文件夹中创建一个多维表格, 包含一个空白的数据表。
//
// 要基于模板创建多维表格, 可先获取模板多维表格 `app_token` 作为文件 token, 再调用[复制文件](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/file/copy)接口创建多维表格。
//
// doc: https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/bitable-v1/app/create
// new doc: https://open.feishu.cn/document/server-docs/docs/bitable-v1/app/create
func (r *BitableService) CreateBitableApp(ctx context.Context, request *CreateBitableAppReq, options ...MethodOptionFunc) (*CreateBitableAppResp, *Response, error) {
	if r.cli.mock.mockBitableCreateBitableApp != nil {
		r.cli.Log(ctx, LogLevelDebug, "[lark] Bitable#CreateBitableApp mock enable")
		return r.cli.mock.mockBitableCreateBitableApp(ctx, request, options...)
	}

	req := &RawRequestReq{
		Scope:                 "Bitable",
		API:                   "CreateBitableApp",
		Method:                "POST",
		URL:                   r.cli.openBaseURL + "/open-apis/bitable/v1/apps",
		Body:                  request,
		MethodOption:          newMethodOption(options),
		NeedTenantAccessToken: true,
		NeedUserAccessToken:   true,
	}
	resp := new(createBitableAppResp)

	response, err := r.cli.RawRequest(ctx, req, resp)
	return resp.Data, response, err
}

// MockBitableCreateBitableApp mock BitableCreateBitableApp method
func (r *Mock) MockBitableCreateBitableApp(f func(ctx context.Context, request *CreateBitableAppReq, options ...MethodOptionFunc) (*CreateBitableAppResp, *Response, error)) {
	r.mockBitableCreateBitableApp = f
}

// UnMockBitableCreateBitableApp un-mock BitableCreateBitableApp method
func (r *Mock) UnMockBitableCreateBitableApp() {
	r.mockBitableCreateBitableApp = nil
}

// CreateBitableAppReq ...
type CreateBitableAppReq struct {
	Name        *string `json:"name,omitempty"`         // 多维表格 App 名称。最长为 255 个字符。示例值: "一篇新的多维表格"
	FolderToken *string `json:"folder_token,omitempty"` // 多维表格 App 归属文件夹。默认为空, 表示多维表格将被创建在云空间根目录。了解如何获取文件夹 Token, 参考[如何获取云文档资源相关 Token](https://open.feishu.cn/document/ukTMukTMukTM/uczNzUjL3czM14yN3MTN#08bb5df6)。注意: 请确保调用身份拥有在该文件夹中的编辑权限。若应用使用的是 `tenant_access_token` 权限, 此处仅可指定应用创建的文件夹。详情参考[如何为应用开通云文档相关资源的权限](https://open.feishu.cn/document/uAjLw4CM/ugTN1YjL4UTN24CO1UjN/trouble-shooting/how-to-add-permissions-to-app)。示例值: "fldcnqquW1svRIYVT2Np6Iabcef"
	TimeZone    *string `json:"time_zone,omitempty"`    // 文档时区, 详情参考[文档时区介绍](https://feishu.feishu.cn/docx/YKRndTM7VoyDqpxqqeEcd67MnEf)。示例值: "Asia/Macau"
}

// CreateBitableAppResp ...
type CreateBitableAppResp struct {
	App *CreateBitableAppRespApp `json:"app,omitempty"` // 返回响应体
}

// CreateBitableAppRespApp ...
type CreateBitableAppRespApp struct {
	AppToken       string `json:"app_token,omitempty"`        // 多维表格的唯一标识 app_token
	Name           string `json:"name,omitempty"`             // 多维表格的名称
	FolderToken    string `json:"folder_token,omitempty"`     // 多维表格 App 归属文件夹
	URL            string `json:"url,omitempty"`              // 多维表格 App 的 URL 链接
	DefaultTableID string `json:"default_table_id,omitempty"` // 默认创建的数据表 ID
	TimeZone       string `json:"time_zone,omitempty"`        // 文档时区
}

// createBitableAppResp ...
type createBitableAppResp struct {
	Code  int64                 `json:"code,omitempty"` // 错误码, 非 0 表示失败
	Msg   string                `json:"msg,omitempty"`  // 错误描述
	Data  *CreateBitableAppResp `json:"data,omitempty"`
	Error *ErrorDetail          `json:"error,omitempty"`
}
