// Code generated by lark_sdk_gen. DO NOT EDIT.
/**
 * Copyright 2022 chyroc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package lark

import (
"context"
)

// SearchHireDiversityInclusion 获取候选人的申请表附加信息。支持通过投递 ID 或者人才 ID 进行查询。
//
// doc: https://open.feishu.cn/document/ukTMukTMukTM/uMzM1YjLzMTN24yMzUjN/hire-v1/diversity_inclusion/search
// 
func (r *HireService) SearchHireDiversityInclusion(ctx context.Context, request *SearchHireDiversityInclusionReq, options ...MethodOptionFunc) (*SearchHireDiversityInclusionResp, *Response, error) {
if r.cli.mock.mockHireSearchHireDiversityInclusion != nil {
		r.cli.Log(ctx, LogLevelDebug, "[lark] Hire#SearchHireDiversityInclusion mock enable")
		return r.cli.mock.mockHireSearchHireDiversityInclusion(ctx, request, options...)
	}

	req := &RawRequestReq{
		Scope:                 "Hire",
		API:                   "SearchHireDiversityInclusion",
		Method:                "POST",
		URL:   r.cli.openBaseURL + "/open-apis/hire/v1/applications/diversity_inclusions/search",
		Body:                  request,
		MethodOption:          newMethodOption(options),
 NeedTenantAccessToken: true,

	}
	resp := new(searchHireDiversityInclusionResp)

	response, err := r.cli.RawRequest(ctx, req, resp)
	return resp.Data, response, err
}

// MockHireSearchHireDiversityInclusion mock HireSearchHireDiversityInclusion method
func (r *Mock) MockHireSearchHireDiversityInclusion(f func(ctx context.Context, request *SearchHireDiversityInclusionReq, options ...MethodOptionFunc) (*SearchHireDiversityInclusionResp, *Response, error)) {
	r.mockHireSearchHireDiversityInclusion = f
}
// UnMockHireSearchHireDiversityInclusion un-mock HireSearchHireDiversityInclusion method
func (r *Mock) UnMockHireSearchHireDiversityInclusion() {
	r.mockHireSearchHireDiversityInclusion = nil
}


// SearchHireDiversityInclusionReq ...
type SearchHireDiversityInclusionReq struct { 
TalentIDs []string `json:"talent_ids,omitempty"` // 人才 ID 列表, 如何获取人才 ID 请参考[获取人才列表](https://open.feishu.cn/document/ukTMukTMukTM/uMzM1YjLzMTN24yMzUjN/hire-v1/talent/list) 特殊说明: 当通过人才 ID 列表查询时会返回对应人才最新投递的申请表附加信息。- 当人才 ID 列表或投递 ID 列表同时存在将以人才 ID 列表为准。- 当人才 ID 列表和投递 ID 列表都没有填写时则返回空数据。示例值: ["6784008015948283905"] 最大长度: `10`
ApplicationIDs []string `json:"application_ids,omitempty"` // 投递 ID 列表, 如何获取投递 ID 请参考[获取投递列表](https://open.feishu.cn/document/ukTMukTMukTM/uMzM1YjLzMTN24yMzUjN/hire-v1/application/list)示例值: ["6784008015948283907"] 最大长度: `30`
}





// SearchHireDiversityInclusionResp ...
type SearchHireDiversityInclusionResp struct { 
Items []*SearchHireDiversityInclusionRespItem `json:"items,omitempty"` // 申请表附加信息列表
}





// SearchHireDiversityInclusionRespItem ...
type SearchHireDiversityInclusionRespItem struct { 
ID string `json:"id,omitempty"` // 附加信息 ID
ApplicationID string `json:"application_id,omitempty"` // 投递ID
TalentID string `json:"talent_id,omitempty"` // 人才ID
SourceType int64 `json:"source_type,omitempty"` // 数据来源可选值有: 官网详情页
CreateTime string `json:"create_time,omitempty"` // 创建时间毫秒时间戳
UpdateTime string `json:"update_time,omitempty"` // 更新时间毫秒时间戳
DiData []*SearchHireDiversityInclusionRespItemDiData `json:"di_data,omitempty"` // 附加信息
}





// SearchHireDiversityInclusionRespItemDiData ...
type SearchHireDiversityInclusionRespItemDiData struct { 
Value string `json:"value,omitempty"` // 字段值 不同类型数据格式如下: 单选: "1" - 多选: "["1", "2"]" - 月份选择: "{"date":"2022-01"}" - 年份选择: "{"date":"2022"}" - 数字: "123" - 单行文本: "今天天气不错" - 多行文本: "该候选人优势如下: 思维敏捷, 逻辑清晰, 对业务有自己见解" - 日期范围: "[1688140800000, 1688140800000]"
ObjectAttribute *SearchHireDiversityInclusionRespItemDiDataObjectAttribute `json:"object_attribute,omitempty"` // 字段属性
}





// SearchHireDiversityInclusionRespItemDiDataObjectAttribute ...
type SearchHireDiversityInclusionRespItemDiDataObjectAttribute struct { 
Title *SearchHireDiversityInclusionRespItemDiDataObjectAttributeTitle `json:"title,omitempty"` // 字段名称
Description *SearchHireDiversityInclusionRespItemDiDataObjectAttributeDescription `json:"description,omitempty"` // 字段描述
DataType int64 `json:"data_type,omitempty"` // 字段类型可选值有: 单选多选月份选择年份选择数字文本多行文本日期范围
Tags []int64 `json:"tags,omitempty"` // 字段标签 可选值有: 1: 性别- 2: 种族- 3: 身体情况
IsFcfData bool `json:"is_fcf_data,omitempty"` // 是否为 FCF 数据FCF: 公平考虑框架( [Fair Consideration Framework](https://www.mom.gov.sg/employment-practices/fair-consideration-framework), 简称 FCF), 该框架规定了所有新加坡的雇主必须平等的考虑新加坡劳动力的就业机会。
IsDiData bool `json:"is_di_data,omitempty"` // 是否为 D&I 数据D&I: 多元化与包容性（Diversity and Inclusion, 简称D&I）, 指的是在组织或社会中, 尊重和重视不同种类的个体, 包括种族、性别、年龄、性取向、宗教、文化背景等。多元化强调个体差异, 而包容性则是在此基础上创建一个尊重、重视并充分利用这些差异的环境。
}





// SearchHireDiversityInclusionRespItemDiDataObjectAttributeDescription ...
type SearchHireDiversityInclusionRespItemDiDataObjectAttributeDescription struct { 
ZhCn string `json:"zh_cn,omitempty"` // 中文
EnUs string `json:"en_us,omitempty"` // 英文
}





// SearchHireDiversityInclusionRespItemDiDataObjectAttributeTitle ...
type SearchHireDiversityInclusionRespItemDiDataObjectAttributeTitle struct { 
ZhCn string `json:"zh_cn,omitempty"` // 中文
EnUs string `json:"en_us,omitempty"` // 英文
}





// searchHireDiversityInclusionResp ...
type searchHireDiversityInclusionResp struct { 
Code int64 `json:"code,omitempty"` // 错误码, 非 0 表示失败
Msg string `json:"msg,omitempty"` // 错误描述
Data *SearchHireDiversityInclusionResp `json:"data,omitempty"` 
Error *ErrorDetail `json:"error,omitempty"` 
}




