// Code generated by lark_sdk_gen. DO NOT EDIT.
/**
 * Copyright 2022 chyroc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package lark

import (
"context"
)

// UpdateCorehrPreHire 通过指定系统字段和自定义字段以更新待入职数据
//
// 该接口会按照应用拥有的「待入职人员」的权限范围返回数据, 请提前在「开发者后台 - 权限管理 - 数据权限-飞书人事(企业版)数据权限范围」中申请「待入职人员」权限范围
//
// doc: https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/pre_hire/patch
// 
func (r *CorehrService) UpdateCorehrPreHire(ctx context.Context, request *UpdateCorehrPreHireReq, options ...MethodOptionFunc) (*UpdateCorehrPreHireResp, *Response, error) {
if r.cli.mock.mockCorehrUpdateCorehrPreHire != nil {
		r.cli.Log(ctx, LogLevelDebug, "[lark] Corehr#UpdateCorehrPreHire mock enable")
		return r.cli.mock.mockCorehrUpdateCorehrPreHire(ctx, request, options...)
	}

	req := &RawRequestReq{
		Scope:                 "Corehr",
		API:                   "UpdateCorehrPreHire",
		Method:                "PATCH",
		URL:   r.cli.openBaseURL + "/open-apis/corehr/v2/pre_hires/:pre_hire_id",
		Body:                  request,
		MethodOption:          newMethodOption(options),
 NeedTenantAccessToken: true,

	}
	resp := new(updateCorehrPreHireResp)

	response, err := r.cli.RawRequest(ctx, req, resp)
	return resp.Data, response, err
}

// MockCorehrUpdateCorehrPreHire mock CorehrUpdateCorehrPreHire method
func (r *Mock) MockCorehrUpdateCorehrPreHire(f func(ctx context.Context, request *UpdateCorehrPreHireReq, options ...MethodOptionFunc) (*UpdateCorehrPreHireResp, *Response, error)) {
	r.mockCorehrUpdateCorehrPreHire = f
}
// UnMockCorehrUpdateCorehrPreHire un-mock CorehrUpdateCorehrPreHire method
func (r *Mock) UnMockCorehrUpdateCorehrPreHire() {
	r.mockCorehrUpdateCorehrPreHire = nil
}


// UpdateCorehrPreHireReq ...
type UpdateCorehrPreHireReq struct { 
PreHireID string `path:"pre_hire_id" json:"-"` // 待入职ID, 可以通过[搜索待入职人员信息](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/pre_hire/search)接口获得示例值: "7345005664477775411"
BasicInfoUpdate *UpdateCorehrPreHireReqBasicInfoUpdate `json:"basic_info_update,omitempty"` // 更新个人（person）信息
OfferInfoUpdate *UpdateCorehrPreHireReqOfferInfoUpdate `json:"offer_info_update,omitempty"` // 更新待入职（prehire）信息
StandardUpdateFields []string `json:"standard_update_fields,omitempty"` // 指定需要更新的系统字段, 只支持最多下钻一层, 格式如下: basic_info_update字段: basic_info_update.names（对name整体进行覆盖更新）；basic_info_update.emails（对邮箱整体进行更新） - offer_info_update字段: offer_info_update.onboarding_method注意, 如果指定了要更新的系统字段但是没有在结构体中传对应的值, 那么就会清空该字段的值示例值: ["basic_info_update.names"]
CustomUpdateFields []string `json:"custom_update_fields,omitempty"` // 指定需要更新的pre_hire对象上的自定义字段, 可以通过[获取自定义字段列表](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/query)接口获得注意: 如果指定了要更新的自定义字段但是没有在结构体中传对应的值, 那么就会清空该字段的值示例值: ["custom_field1__c"]
PersonCustomUpdateFields []string `json:"person_custom_update_fields,omitempty"` // 指定需要更新的person对象上的自定义字段, 可以通过[获取自定义字段列表](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/query)接口获得注意: 如果指定了要更新的自定义字段但是没有在结构体中传对应的值, 那么就会清空该字段的值示例值: ["custom_field1__c"]
}





// UpdateCorehrPreHireReqBasicInfoUpdate ...
type UpdateCorehrPreHireReqBasicInfoUpdate struct { 
Names []*UpdateCorehrPreHireReqBasicInfoUpdateName `json:"names,omitempty"` // 姓名, 该值是一个list, 会全量更新。即使只更新 list 中的某一个元素, 也需要把其它元素都完整传值, 否则将丢失数据。
Phones []*UpdateCorehrPreHireReqBasicInfoUpdatePhone `json:"phones,omitempty"` // 电话, 该值是一个list, 会全量更新。即使只更新 list 中的某一个元素, 也需要把其它元素都完整传值, 否则将丢失数据。
Emails []*UpdateCorehrPreHireReqBasicInfoUpdateEmail `json:"emails,omitempty"` // 邮箱, 该值是一个list, 会全量更新。即使只更新 list 中的某一个元素, 也需要把其它元素都完整传值, 否则将丢失数据。
NationalityV2ID *string `json:"nationality_v2_id,omitempty"` // 国籍, 可以通过[查询国籍信息](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/basic_info-nationality/search)接口获取示例值: "6862995757234914824"
AdditionalNationalityIDList []string `json:"additional_nationality_id_list,omitempty"` // 其他国籍, 可以通过[查询国籍信息](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/basic_info-nationality/search)接口获取示例值: ["6862995757234914824"]
ResidentTaxList []*UpdateCorehrPreHireReqBasicInfoUpdateResidentTax `json:"resident_tax_list,omitempty"` // 纳税身份信息, 该值是一个list, 会全量更新
BornCountryRegion *string `json:"born_country_region,omitempty"` // 出生国家/地区, 可以通过接口[查询国家/地区信息](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/basic_info-country_region/search)获得示例值: "6862995757234914824"
IsDisabled *bool `json:"is_disabled,omitempty"` // 是否残疾示例值: true
DisableCardNumber *string `json:"disable_card_number,omitempty"` // 残疾证号示例值: "身份证号+残疾类型（1-7）+ 残疾程度分级（1-4）+[补发编号]"
IsOldAlone *bool `json:"is_old_alone,omitempty"` // 是否孤老示例值: true
IsMartyrFamily *bool `json:"is_martyr_family,omitempty"` // 是否烈属示例值: true
MartyrCardNumber *string `json:"martyr_card_number,omitempty"` // 烈属证号示例值: "00001"
DependentList []*UpdateCorehrPreHireReqBasicInfoUpdateDependent `json:"dependent_list,omitempty"` // 家庭成员
Religion *string `json:"religion,omitempty"` // 宗教信仰, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name: person- custom_api_name: religion示例值: "buddism"
BankAccountList []*UpdateCorehrPreHireReqBasicInfoUpdateBankAccount `json:"bank_account_list,omitempty"` // 银行账号
NationalIDList []*UpdateCorehrPreHireReqBasicInfoUpdateNationalID `json:"national_id_list,omitempty"` // 证件账号
PersonalProfileList []*UpdateCorehrPreHireReqBasicInfoUpdatePersonalProfile `json:"personal_profile_list,omitempty"` // 个人资料
EmergencyContactList []*UpdateCorehrPreHireReqBasicInfoUpdateEmergencyContact `json:"emergency_contact_list,omitempty"` // 紧急联系人
AddressList []*UpdateCorehrPreHireReqBasicInfoUpdateAddress `json:"address_list,omitempty"` // 联系地址
MaritalStatus *string `json:"marital_status,omitempty"` // 婚姻状况, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name: person- custom_api_name: marital_status示例值: "single"
EthnicityRace *string `json:"ethnicity_race,omitempty"` // 民族 / 种族, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name: person- custom_api_name: ethnicity_race示例值: "han"
CustomFields []*UpdateCorehrPreHireReqBasicInfoUpdateCustomField `json:"custom_fields,omitempty"` // 自定义字段
NativeRegion *string `json:"native_region,omitempty"` // 籍贯, 可以通过[查询省份/行政区信息](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/basic_info-country_region_subdivision/search)接口获取示例值: "6862995757234914824"
HukouType *string `json:"hukou_type,omitempty"` // 户口类型, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name: person_info_chn- custom_api_name: hukou_type示例值: "local_urban_residence"
HukouLocation *string `json:"hukou_location,omitempty"` // 户口所在地示例值: "北京市海淀区北三环西路"
GenderID *string `json:"gender_id,omitempty"` // 性别, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name: dependent- custom_api_name: gender示例值: "male"
DateOfBirth *string `json:"date_of_birth,omitempty"` // 生日示例值: "2011-99-99"
DateEnteredWorkforce *string `json:"date_entered_workforce,omitempty"` // 参加工作日期示例值: "2100-09-09"
ExpectedGraduateDate *string `json:"expected_graduate_date,omitempty"` // 预计毕业日期示例值: "2023-01-10"
CitizenshipStatusIDList []string `json:"citizenship_status_id_list,omitempty"` // 公民身份示例值: ["6862995757234914824"]
WorkExperience []*UpdateCorehrPreHireReqBasicInfoUpdateWorkExperience `json:"work_experience,omitempty"` // 工作履历
EducationInfo []*UpdateCorehrPreHireReqBasicInfoUpdateEducationInfo `json:"education_info,omitempty"` // 教育经历
}





// UpdateCorehrPreHireReqBasicInfoUpdateAddress ...
type UpdateCorehrPreHireReqBasicInfoUpdateAddress struct { 
CountryRegionID string `json:"country_region_id,omitempty"` // 国家 / 地区, 可以通过接口[查询国家/地区信息](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/basic_info-country_region/search)获得示例值: "6862995757234914824"
RegionID *string `json:"region_id,omitempty"` // 主要行政区, 可以通过接口[查询省份/行政区信息](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/basic_info-country_region_subdivision/search)获得示例值: "6863326815667095047"
LocalAddressLine1 *string `json:"local_address_line1,omitempty"` // 地址行 1（非拉丁语系的本地文字）示例值: "北京市海淀区"
LocalAddressLine2 *string `json:"local_address_line2,omitempty"` // 地址行 2（非拉丁语系的本地文字）示例值: "上海市杨浦区"
LocalAddressLine3 *string `json:"local_address_line3,omitempty"` // 地址行 3（非拉丁语系的本地文字）示例值: "北京市房山区"
LocalAddressLine4 *string `json:"local_address_line4,omitempty"` // 地址行 4（非拉丁语系的本地文字）示例值: "天津滨海高新区"
LocalAddressLine5 *string `json:"local_address_line5,omitempty"` // 地址行 5（非拉丁语系的本地文字）示例值: "成都市成华区"
LocalAddressLine6 *string `json:"local_address_line6,omitempty"` // 地址行 6（非拉丁语系的本地文字）示例值: "深圳市南山区"
LocalAddressLine7 *string `json:"local_address_line7,omitempty"` // 地址行 7（非拉丁语系的本地文字）示例值: "南京市鼓楼区"
LocalAddressLine8 *string `json:"local_address_line8,omitempty"` // 地址行 8（非拉丁语系的本地文字）示例值: "杭州市滨江区"
LocalAddressLine9 *string `json:"local_address_line9,omitempty"` // 地址行 9（非拉丁语系的本地文字）示例值: "郑州市中原区"
PostalCode *string `json:"postal_code,omitempty"` // 邮政编码示例值: "611530"
AddressTypes []string `json:"address_types,omitempty"` // 地址类型, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name: address- custom_api_name: address_type示例值: ["home_address"] 长度范围: `1` ～ `1000`
IsPrimary bool `json:"is_primary,omitempty"` // 主要地址示例值: true
IsPublic bool `json:"is_public,omitempty"` // 公开地址示例值: true
CityIDV2 *string `json:"city_id_v2,omitempty"` // 城市示例值: "6863333254578046471"
DistrictIDV2 *string `json:"district_id_v2,omitempty"` // 区/县示例值: "6863333516579440141"
}





// UpdateCorehrPreHireReqBasicInfoUpdateBankAccount ...
type UpdateCorehrPreHireReqBasicInfoUpdateBankAccount struct { 
BankName *string `json:"bank_name,omitempty"` // 银行名称示例值: "中国农业银行"
BranchName *string `json:"branch_name,omitempty"` // 支行名称示例值: "中国农业银行支行"
BankAccountNumber string `json:"bank_account_number,omitempty"` // 银行账号示例值: "6231200xxxx01223"
AccountHolder string `json:"account_holder,omitempty"` // 开户人姓名示例值: "孟十五"
CountryRegionID *string `json:"country_region_id,omitempty"` // 国家/地区 ID, 可以通过接口[查询国家/地区信息](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/basic_info-country_region/search)获得示例值: "6862995745889322510"
BankAccountUsages []string `json:"bank_account_usages,omitempty"` // 银行卡用途, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name: bank_account- custom_api_name: bank_account_usage示例值: ["payment"] 长度范围: `0` ～ `100`
BankAccountType *string `json:"bank_account_type,omitempty"` // 银行卡类型, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name: bank_account- custom_api_name: bank_account_type示例值: "checking"
CustomFields []*UpdateCorehrPreHireReqBasicInfoUpdateBankAccountCustomField `json:"custom_fields,omitempty"` // 自定义字段
}





// UpdateCorehrPreHireReqBasicInfoUpdateBankAccountCustomField ...
type UpdateCorehrPreHireReqBasicInfoUpdateBankAccountCustomField struct { 
FieldName string `json:"field_name,omitempty"` // 字段名示例值: "name"
Value string `json:"value,omitempty"` // 字段值, 是json转义后的字符串, 根据元数据定义不同, 字段格式不同(123, 123.23, true, [\"id1\", \"id2\], 2006-01-02 15:04:05])示例值: "Sandy"
}





// UpdateCorehrPreHireReqBasicInfoUpdateCustomField ...
type UpdateCorehrPreHireReqBasicInfoUpdateCustomField struct { 
FieldName string `json:"field_name,omitempty"` // 字段名示例值: "name"
Value string `json:"value,omitempty"` // 字段值, 是json转义后的字符串, 根据元数据定义不同, 字段格式不同(123, 123.23, true, [\"id1\", \"id2\], 2006-01-02 15:04:05)示例值: "Sandy"
}





// UpdateCorehrPreHireReqBasicInfoUpdateDependent ...
type UpdateCorehrPreHireReqBasicInfoUpdateDependent struct { 
Relationship string `json:"relationship,omitempty"` // 关系, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name: dependent- custom_api_name: relationship_with_dependent示例值: "parent"
Gender *string `json:"gender,omitempty"` // 性别, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name: dependent- custom_api_name: gender示例值: "male"
DateOfBirth *string `json:"date_of_birth,omitempty"` // 生日示例值: "2020-01-01"
NationalIDs []string `json:"national_ids,omitempty"` // 证件号码 长度范围: `1` ～ `1000`
SpousesWorkingStatus *string `json:"spouses_working_status,omitempty"` // 配偶工作状态, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name: dependent- custom_api_name: spouses_working_status示例值: "working"
IsThisPersonCoveredByHealthInsurance *bool `json:"is_this_person_covered_by_health_insurance,omitempty"` // 包含家属医疗保险示例值: true
IsThisPersonAllowedForTaxDeduction *bool `json:"is_this_person_allowed_for_tax_deduction,omitempty"` // 允许家属抵扣税款示例值: false
DependentName *string `json:"dependent_name,omitempty"` // 家庭成员姓名示例值: "王冰"
Employer *string `json:"employer,omitempty"` // 工作单位示例值: "海淀区交警大队"
Job *string `json:"job,omitempty"` // 岗位信息描述示例值: "保安"
Phone *UpdateCorehrPreHireReqBasicInfoUpdateDependentPhone `json:"phone,omitempty"` // 电话
Address *UpdateCorehrPreHireReqBasicInfoUpdateDependentAddress `json:"address,omitempty"` // 联系地址
CustomFields []*UpdateCorehrPreHireReqBasicInfoUpdateDependentCustomField `json:"custom_fields,omitempty"` // 自定义字段
}





// UpdateCorehrPreHireReqBasicInfoUpdateDependentAddress ...
type UpdateCorehrPreHireReqBasicInfoUpdateDependentAddress struct { 
CountryRegionID string `json:"country_region_id,omitempty"` // 国家 / 地区, 可以通过接口[查询国家/地区信息](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/basic_info-country_region/search)获得示例值: "6862995757234914824"
RegionID *string `json:"region_id,omitempty"` // 主要行政区, 可以通过接口[查询省份/行政区信息](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/basic_info-country_region_subdivision/search)获得示例值: "6863326815667095047"
LocalAddressLine1 *string `json:"local_address_line1,omitempty"` // 地址行 1（非拉丁语系的本地文字）示例值: "北京市海淀区"
LocalAddressLine2 *string `json:"local_address_line2,omitempty"` // 地址行 2（非拉丁语系的本地文字）示例值: "上海市杨浦区"
LocalAddressLine3 *string `json:"local_address_line3,omitempty"` // 地址行 3（非拉丁语系的本地文字）示例值: "北京市房山区"
LocalAddressLine4 *string `json:"local_address_line4,omitempty"` // 地址行 4（非拉丁语系的本地文字）示例值: "天津滨海高新区"
LocalAddressLine5 *string `json:"local_address_line5,omitempty"` // 地址行 5（非拉丁语系的本地文字）示例值: "成都市成华区"
LocalAddressLine6 *string `json:"local_address_line6,omitempty"` // 地址行 6（非拉丁语系的本地文字）示例值: "深圳市南山区"
LocalAddressLine7 *string `json:"local_address_line7,omitempty"` // 地址行 7（非拉丁语系的本地文字）示例值: "南京市鼓楼区"
LocalAddressLine8 *string `json:"local_address_line8,omitempty"` // 地址行 8（非拉丁语系的本地文字）示例值: "杭州市滨江区"
LocalAddressLine9 *string `json:"local_address_line9,omitempty"` // 地址行 9（非拉丁语系的本地文字）示例值: "郑州市中原区"
PostalCode *string `json:"postal_code,omitempty"` // 邮政编码示例值: "611530"
AddressTypes []string `json:"address_types,omitempty"` // 地址类型, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name: address- custom_api_name: address_type示例值: ["home_address"] 长度范围: `1` ～ `1000`
IsPrimary bool `json:"is_primary,omitempty"` // 主要地址示例值: true
IsPublic bool `json:"is_public,omitempty"` // 公开地址示例值: true
CityIDV2 *string `json:"city_id_v2,omitempty"` // 城市示例值: "6863333254578046471"
DistrictIDV2 *string `json:"district_id_v2,omitempty"` // 区/县示例值: "6863333516579440141"
}





// UpdateCorehrPreHireReqBasicInfoUpdateDependentCustomField ...
type UpdateCorehrPreHireReqBasicInfoUpdateDependentCustomField struct { 
FieldName string `json:"field_name,omitempty"` // 字段名示例值: "name"
Value string `json:"value,omitempty"` // 字段值, 是json转义后的字符串, 根据元数据定义不同, 字段格式不同(123, 123.23, true, [\"id1\", \"id2\], 2006-01-02 15:04:05])示例值: "Sandy"
}





// UpdateCorehrPreHireReqBasicInfoUpdateDependentPhone ...
type UpdateCorehrPreHireReqBasicInfoUpdateDependentPhone struct { 
InternationalAreaCode string `json:"international_area_code,omitempty"` // 国家区号, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name: phone- custom_api_name: international_area_code示例值: "86_china"
PhoneNumber string `json:"phone_number,omitempty"` // 电话号码示例值: "178xxxx1232"
DeviceType string `json:"device_type,omitempty"` // 设备类型, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name: phone- custom_api_name: device_type示例值: "mobile_phone"
PhoneUsage string `json:"phone_usage,omitempty"` // 电话用途, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name: phone- custom_api_name: phone_usage示例值: "home"
IsPrimary bool `json:"is_primary,omitempty"` // 主要电话, 若有多个电话, 只能有一个电话的「is_primary」为true示例值: true
IsPublic bool `json:"is_public,omitempty"` // 公开电话示例值: true
}





// UpdateCorehrPreHireReqBasicInfoUpdateEducationInfo ...
type UpdateCorehrPreHireReqBasicInfoUpdateEducationInfo struct { 
SchoolName *string `json:"school_name,omitempty"` // 学校名称示例值: "长安大学"
Education *string `json:"education,omitempty"` // 学历, 枚举值可通过文档[枚举常量介绍](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/feishu-people-enum-constant)学历（level_of_education）枚举定义获得示例值: "phd"
StartTime *string `json:"start_time,omitempty"` // 开始时间示例值: "2017-04-01"
EndTime *string `json:"end_time,omitempty"` // 结束时间示例值: "2018-04-01"
FieldOfStudy *string `json:"field_of_study,omitempty"` // 专业示例值: "医学影像技术"
}





// UpdateCorehrPreHireReqBasicInfoUpdateEmail ...
type UpdateCorehrPreHireReqBasicInfoUpdateEmail struct { 
Email string `json:"email,omitempty"` // 邮箱地址示例值: "1234567@bytedance.com"
IsPrimary bool `json:"is_primary,omitempty"` // 是否为主要邮箱, 若有多个邮箱, 只能有一个邮箱的「is_primary」为true示例值: true
IsPublic bool `json:"is_public,omitempty"` // 是否为公开邮箱示例值: true
EmailUsage string `json:"email_usage,omitempty"` // 邮箱用途, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name = email- custom_api_name = email_usage示例值: "work"
}





// UpdateCorehrPreHireReqBasicInfoUpdateEmergencyContact ...
type UpdateCorehrPreHireReqBasicInfoUpdateEmergencyContact struct { 
LegalName *string `json:"legal_name,omitempty"` // 紧急联系人姓名示例值: "王冰"
Relationship *string `json:"relationship,omitempty"` // 紧急联系人与本人亲属关系, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name: emergency_contact- custom_api_name: relationship示例值: "parent"
Phones []*UpdateCorehrPreHireReqBasicInfoUpdateEmergencyContactPhone `json:"phones,omitempty"` // 电话 长度范围: `0` ～ `1000`
Address *UpdateCorehrPreHireReqBasicInfoUpdateEmergencyContactAddress `json:"address,omitempty"` // 地址
Email *UpdateCorehrPreHireReqBasicInfoUpdateEmergencyContactEmail `json:"email,omitempty"` // 邮箱
IsPrimary *bool `json:"is_primary,omitempty"` // 主要联系人, 若有多个联系人, 只能有一个联系人的「is_primary」为true示例值: true
CustomFields []*UpdateCorehrPreHireReqBasicInfoUpdateEmergencyContactCustomField `json:"custom_fields,omitempty"` // 自定义字段
}





// UpdateCorehrPreHireReqBasicInfoUpdateEmergencyContactAddress ...
type UpdateCorehrPreHireReqBasicInfoUpdateEmergencyContactAddress struct { 
CountryRegionID string `json:"country_region_id,omitempty"` // 国家 / 地区, 可以通过接口[查询国家/地区信息](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/basic_info-country_region/search)获得示例值: "6862995757234914824"
RegionID *string `json:"region_id,omitempty"` // 主要行政区, 可以通过接口[查询省份/行政区信息](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/basic_info-country_region_subdivision/search)获得示例值: "6863326815667095047"
LocalAddressLine1 *string `json:"local_address_line1,omitempty"` // 地址行 1（非拉丁语系的本地文字）示例值: "北京市海淀区"
LocalAddressLine2 *string `json:"local_address_line2,omitempty"` // 地址行 2（非拉丁语系的本地文字）示例值: "上海市杨浦区"
LocalAddressLine3 *string `json:"local_address_line3,omitempty"` // 地址行 3（非拉丁语系的本地文字）示例值: "北京市房山区"
LocalAddressLine4 *string `json:"local_address_line4,omitempty"` // 地址行 4（非拉丁语系的本地文字）示例值: "天津滨海高新区"
LocalAddressLine5 *string `json:"local_address_line5,omitempty"` // 地址行 5（非拉丁语系的本地文字）示例值: "成都市成华区"
LocalAddressLine6 *string `json:"local_address_line6,omitempty"` // 地址行 6（非拉丁语系的本地文字）示例值: "深圳市南山区"
LocalAddressLine7 *string `json:"local_address_line7,omitempty"` // 地址行 7（非拉丁语系的本地文字）示例值: "南京市鼓楼区"
LocalAddressLine8 *string `json:"local_address_line8,omitempty"` // 地址行 8（非拉丁语系的本地文字）示例值: "杭州市滨江区"
LocalAddressLine9 *string `json:"local_address_line9,omitempty"` // 地址行 9（非拉丁语系的本地文字）示例值: "郑州市中原区"
PostalCode *string `json:"postal_code,omitempty"` // 邮政编码示例值: "611530"
AddressTypes []string `json:"address_types,omitempty"` // 地址类型, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name: address- custom_api_name: address_type示例值: ["home_address"] 长度范围: `1` ～ `1000`
IsPrimary bool `json:"is_primary,omitempty"` // 主要地址示例值: true
IsPublic bool `json:"is_public,omitempty"` // 公开地址示例值: true
CityIDV2 *string `json:"city_id_v2,omitempty"` // 城市示例值: "6863333254578046471"
DistrictIDV2 *string `json:"district_id_v2,omitempty"` // 区/县示例值: "6863333516579440141"
}





// UpdateCorehrPreHireReqBasicInfoUpdateEmergencyContactCustomField ...
type UpdateCorehrPreHireReqBasicInfoUpdateEmergencyContactCustomField struct { 
FieldName string `json:"field_name,omitempty"` // 字段名示例值: "name"
Value string `json:"value,omitempty"` // 字段值, 是json转义后的字符串, 根据元数据定义不同, 字段格式不同(123, 123.23, true, [\"id1\", \"id2\], 2006-01-02 15:04:05])示例值: "Sandy"
}





// UpdateCorehrPreHireReqBasicInfoUpdateEmergencyContactEmail ...
type UpdateCorehrPreHireReqBasicInfoUpdateEmergencyContactEmail struct { 
Email string `json:"email,omitempty"` // 邮箱地址示例值: "1234567@bytedance.com"
IsPrimary bool `json:"is_primary,omitempty"` // 是否为主要邮箱, 若有多个邮箱, 只能有一个邮箱的「is_primary」为true示例值: true
IsPublic bool `json:"is_public,omitempty"` // 是否为公开邮箱示例值: true
EmailUsage string `json:"email_usage,omitempty"` // 邮箱用途, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name: email- custom_api_name: email_usage示例值: "work"
}





// UpdateCorehrPreHireReqBasicInfoUpdateEmergencyContactPhone ...
type UpdateCorehrPreHireReqBasicInfoUpdateEmergencyContactPhone struct { 
InternationalAreaCode string `json:"international_area_code,omitempty"` // 国家区号, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name: phone- custom_api_name: international_area_code示例值: "86_china"
PhoneNumber string `json:"phone_number,omitempty"` // 电话号码示例值: "178xxxx1232"
DeviceType string `json:"device_type,omitempty"` // 设备类型, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name: phone- custom_api_name: device_type示例值: "mobile_phone"
PhoneUsage string `json:"phone_usage,omitempty"` // 电话用途, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name: phone- custom_api_name: phone_usage示例值: "home"
IsPrimary bool `json:"is_primary,omitempty"` // 主要电话, 若有多个电话, 只能有一个电话的「is_primary」为true示例值: true
IsPublic bool `json:"is_public,omitempty"` // 公开电话示例值: true
}





// UpdateCorehrPreHireReqBasicInfoUpdateName ...
type UpdateCorehrPreHireReqBasicInfoUpdateName struct { 
FullName *string `json:"full_name,omitempty"` // 全名示例值: "李一一"
FirstName *string `json:"first_name,omitempty"` // 名示例值: "一"
MiddleName *string `json:"middle_name,omitempty"` // 中间名示例值: "一"
NamePrimary *string `json:"name_primary,omitempty"` // 姓示例值: "李"
LocalFirstName *string `json:"local_first_name,omitempty"` // 名 - 本地文字示例值: "一"
LocalMiddleName *string `json:"local_middle_name,omitempty"` // 本地中间名示例值: "一"
LocalPrimary *string `json:"local_primary,omitempty"` // 姓 - 本地文字示例值: "李"
CustomLocalName *string `json:"custom_local_name,omitempty"` // 自定义姓名（本地文字）示例值: "李一一"
CustomWesternName *string `json:"custom_western_name,omitempty"` // 自定义姓名（西方文字）示例值: "YiyiLi"
CountryRegion string `json:"country_region,omitempty"` // 国家/地区, 可以通过接口[查询国家/地区信息](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/basic_info-country_region/search)获得示例值: "6862995757234914824"
NameType string `json:"name_type,omitempty"` // 姓名类型, 枚举值如下: legal_name: 法定姓名- preferred_name: 常用名- former_name: 曾用名- additional_name: 别名示例值: "legal_name"
AdditionalName *string `json:"additional_name,omitempty"` // 别名示例值: "别名"
}





// UpdateCorehrPreHireReqBasicInfoUpdateNationalID ...
type UpdateCorehrPreHireReqBasicInfoUpdateNationalID struct { 
CountryRegionID string `json:"country_region_id,omitempty"` // 国家 / 地区, 可以通过接口[查询国家/地区信息](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/basic_info-country_region/search)获得示例值: "6862995757234914824"
NationalIDTypeID string `json:"national_id_type_id,omitempty"` // 国家证件类型, 可以通过[批量查询国家证件类型](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/national_id_type/list)接口获得示例值: "6863330041896371725"
NationalIDNumber string `json:"national_id_number,omitempty"` // 证件号码示例值: "1231131333"
IssueDate *string `json:"issue_date,omitempty"` // 证件签发日期示例值: "2020-04-01"
ExpirationDate *string `json:"expiration_date,omitempty"` // 证件到期日期示例值: "2020-05-21"
IssuedBy *string `json:"issued_by,omitempty"` // 证件签发机构示例值: "北京市公安局"
CustomFields []*UpdateCorehrPreHireReqBasicInfoUpdateNationalIDCustomField `json:"custom_fields,omitempty"` // 自定义字段
}





// UpdateCorehrPreHireReqBasicInfoUpdateNationalIDCustomField ...
type UpdateCorehrPreHireReqBasicInfoUpdateNationalIDCustomField struct { 
FieldName string `json:"field_name,omitempty"` // 字段名示例值: "name"
Value string `json:"value,omitempty"` // 字段值, 是json转义后的字符串, 根据元数据定义不同, 字段格式不同(123, 123.23, true, [\"id1\", \"id2\], 2006-01-02 15:04:05])示例值: "Sandy"
}





// UpdateCorehrPreHireReqBasicInfoUpdatePersonalProfile ...
type UpdateCorehrPreHireReqBasicInfoUpdatePersonalProfile struct { 
PersonalProfileType *string `json:"personal_profile_type,omitempty"` // 资料类型, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name: personal_profile- custom_api_name: profile_type示例值: "profile_type_1_101_101011"
Files []*UpdateCorehrPreHireReqBasicInfoUpdatePersonalProfileFile `json:"files,omitempty"` // 资料文件列表 长度范围: `0` ～ `1000`
}





// UpdateCorehrPreHireReqBasicInfoUpdatePersonalProfileFile ...
type UpdateCorehrPreHireReqBasicInfoUpdatePersonalProfileFile struct { 
ID *string `json:"id,omitempty"` // 文件ID, 通过[上传文件](/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/person/upload)接口上传文件后, 获取文件ID示例值: "6655aa1b2ec326f983b91f9d_f9974583040c4b05ae71f92f5df16bbc"
}





// UpdateCorehrPreHireReqBasicInfoUpdatePhone ...
type UpdateCorehrPreHireReqBasicInfoUpdatePhone struct { 
InternationalAreaCode string `json:"international_area_code,omitempty"` // 电话区号, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name = phone- custom_api_name = international_area_code示例值: "86_china"
PhoneNumber string `json:"phone_number,omitempty"` // 电话号码示例值: "178xxxx1234"
DeviceType string `json:"device_type,omitempty"` // 设备类型, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name = phone- custom_api_name = device_type示例值: "mobile_phone"
PhoneUsage string `json:"phone_usage,omitempty"` // 电话用途, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name = phone- custom_api_name = phone_usage示例值: "work"
IsPrimary bool `json:"is_primary,omitempty"` // 主要电话, 若有多个电话, 只能有一个电话的「is_primary」为true示例值: true
IsPublic bool `json:"is_public,omitempty"` // 公开电话示例值: true
}





// UpdateCorehrPreHireReqBasicInfoUpdateResidentTax ...
type UpdateCorehrPreHireReqBasicInfoUpdateResidentTax struct { 
TaxCountryRegion *string `json:"tax_country_region,omitempty"` // 国家 / 地区ID, 可以通过接口[查询国家/地区信息](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/basic_info-country_region/search)获得示例值: "6862995757234914824"
ResidentStatus *string `json:"resident_status,omitempty"` // 居民身份示例值: "tax_residence"
TaxAddress *UpdateCorehrPreHireReqBasicInfoUpdateResidentTaxTaxAddress `json:"tax_address,omitempty"` // 纳税地址
ResidentStatusSpecification *string `json:"resident_status_specification,omitempty"` // 居民纳税身份说明示例值: "文本内容, 对纳税身份的补充说明信息"
YearResidentTax *string `json:"year_resident_tax,omitempty"` // 年度示例值: "2006-01-01"
CustomFields []*UpdateCorehrPreHireReqBasicInfoUpdateResidentTaxCustomField `json:"custom_fields,omitempty"` // 自定义字段
}





// UpdateCorehrPreHireReqBasicInfoUpdateResidentTaxCustomField ...
type UpdateCorehrPreHireReqBasicInfoUpdateResidentTaxCustomField struct { 
FieldName string `json:"field_name,omitempty"` // 字段名示例值: "name"
Value string `json:"value,omitempty"` // 字段值, 是json转义后的字符串, 根据元数据定义不同, 字段格式不同(123, 123.23, true, [\"id1\", \"id2\], 2006-01-02 15:04:05])示例值: "Sandy"
}





// UpdateCorehrPreHireReqBasicInfoUpdateResidentTaxTaxAddress ...
type UpdateCorehrPreHireReqBasicInfoUpdateResidentTaxTaxAddress struct { 
CountryRegionID string `json:"country_region_id,omitempty"` // 国家 / 地区, 可以通过接口[查询国家/地区信息](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/basic_info-country_region/search)获得示例值: "6862995757234914824"
RegionID *string `json:"region_id,omitempty"` // 主要行政区, 可以通过接口[查询省份/行政区信息](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/basic_info-country_region_subdivision/search)获得示例值: "6863326815667095047"
LocalAddressLine1 *string `json:"local_address_line1,omitempty"` // 地址行 1（非拉丁语系的本地文字）示例值: "北京市海淀区"
LocalAddressLine2 *string `json:"local_address_line2,omitempty"` // 地址行 2（非拉丁语系的本地文字）示例值: "上海市杨浦区"
LocalAddressLine3 *string `json:"local_address_line3,omitempty"` // 地址行 3（非拉丁语系的本地文字）示例值: "北京市房山区"
LocalAddressLine4 *string `json:"local_address_line4,omitempty"` // 地址行 4（非拉丁语系的本地文字）示例值: "天津滨海高新区"
LocalAddressLine5 *string `json:"local_address_line5,omitempty"` // 地址行 5（非拉丁语系的本地文字）示例值: "成都市成华区"
LocalAddressLine6 *string `json:"local_address_line6,omitempty"` // 地址行 6（非拉丁语系的本地文字）示例值: "深圳市南山区"
LocalAddressLine7 *string `json:"local_address_line7,omitempty"` // 地址行 7（非拉丁语系的本地文字）示例值: "南京市鼓楼区"
LocalAddressLine8 *string `json:"local_address_line8,omitempty"` // 地址行 8（非拉丁语系的本地文字）示例值: "杭州市滨江区"
LocalAddressLine9 *string `json:"local_address_line9,omitempty"` // 地址行 9（非拉丁语系的本地文字）示例值: "郑州市中原区"
PostalCode *string `json:"postal_code,omitempty"` // 邮政编码示例值: "611530"
AddressTypes []string `json:"address_types,omitempty"` // 地址类型, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name: address- custom_api_name: address_type示例值: ["home_address"] 长度范围: `1` ～ `1000`
IsPrimary bool `json:"is_primary,omitempty"` // 主要地址示例值: true
IsPublic bool `json:"is_public,omitempty"` // 公开地址示例值: true
CityIDV2 *string `json:"city_id_v2,omitempty"` // 城市, 可以通过接口[查询城市信息](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/basic_info-city/search)获取详情示例值: "6863333254578046471"
DistrictIDV2 *string `json:"district_id_v2,omitempty"` // 区/县, 可以通过接口[查询区/县信息](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/basic_info-district/search)获取详情示例值: "6863333516579440141"
}





// UpdateCorehrPreHireReqBasicInfoUpdateWorkExperience ...
type UpdateCorehrPreHireReqBasicInfoUpdateWorkExperience struct { 
CompanyName *string `json:"company_name,omitempty"` // 公司名称示例值: "猎豹"
StartTime *string `json:"start_time,omitempty"` // 开始时间示例值: "2015-02-01"
EndTime *string `json:"end_time,omitempty"` // 结束时间示例值: "2017-02-01"
JobTitle *string `json:"job_title,omitempty"` // 岗位示例值: "产品经理"
Description *string `json:"description,omitempty"` // 工作描述示例值: "app"
Department *string `json:"department,omitempty"` // 部门示例值: "部门名称"
}





// UpdateCorehrPreHireReqOfferInfoUpdate ...
type UpdateCorehrPreHireReqOfferInfoUpdate struct { 
OnboardingDate *string `json:"onboarding_date,omitempty"` // 入职日期示例值: "2022-10-08"
AtsApplicationID *string `json:"ats_application_id,omitempty"` // 招聘应用 ID, 仅支持飞书招聘 ID, 可以通过[获取投递列表](https://open.feishu.cn/document/ukTMukTMukTM/uMzM1YjLzMTN24yMzUjN/hire-v1/application/list)接口获取示例值: "7140946969586010376"
OnboardingLocationID *string `json:"onboarding_location_id,omitempty"` // 入职地点ID, 可以通过[批量查询地点](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/location/list)接口获得示例值: "6977976687350924832"
OnboardingAddressID *string `json:"onboarding_address_id,omitempty"` // 入职地址ID, 可以通过[批量查询地点](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/location/list)接口获得示例值: "6977976687350924832"
OfficeLocationID *string `json:"office_location_id,omitempty"` // 办公地点ID, 可以通过[批量查询地点](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/location/list)接口获得示例值: "6977976687350924833"
OfficeAddressID *string `json:"office_address_id,omitempty"` // 办公地址ID, 可以通过[批量查询地点](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/location/list)接口获得示例值: "6977976687350924832"
EmploymentType *string `json:"employment_type,omitempty"` // 雇佣类型, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name = pre_hire- custom_api_name = employment_type示例值: "employee"
OnboardingMethod *string `json:"onboarding_method,omitempty"` // 入职方式, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name = pre_hire- custom_api_name = onboarding_method示例值: "onsite"
WorkEmails []*UpdateCorehrPreHireReqOfferInfoUpdateWorkEmail `json:"work_emails,omitempty"` // 工作邮箱, 该值是一个list, 会全量更新。即使只更新 list 中的某一个元素, 也需要把其它元素都完整传值, 否则将丢失数据。
CostCenterRates []*UpdateCorehrPreHireReqOfferInfoUpdateCostCenterRate `json:"cost_center_rates,omitempty"` // 成本中心分摊信息- 待废弃, 建议使用cost_allocation
CustomFields []*UpdateCorehrPreHireReqOfferInfoUpdateCustomField `json:"custom_fields,omitempty"` // 自定义字段
PositionID *string `json:"position_id,omitempty"` // 岗位id, 如需获取具体值, 请联系人员档案管理员示例值: "697797668735092768"
ProbationPeriod *int64 `json:"probation_period,omitempty"` // 试用期时长示例值: 6
ProbationStartDate *string `json:"probation_start_date,omitempty"` // 试用期开始日期, 格式: "YYYY-MM-DD"示例值: "2022-07-29"
ProbationEndDate *string `json:"probation_end_date,omitempty"` // 试用期结束日期, 格式: "YYYY-MM-DD"示例值: "2023-04-07"
ContractStartDate *string `json:"contract_start_date,omitempty"` // 合同开始日期, 格式: "YYYY-MM-DD"示例值: "2022-10-08"
ContractEndDate *string `json:"contract_end_date,omitempty"` // 合同结束日期, 格式: "YYYY-MM-DD"示例值: "2025-10-07"
ContractType *string `json:"contract_type,omitempty"` // 合同类型, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name: pre_hire- custom_api_name: contract_type示例值: "internship_agreement"
DurationTypeID *string `json:"duration_type_id,omitempty"` // 期限类型, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name: pre_hire- custom_api_name: duration_type示例值: "fixed_term"
SigningTypeID *string `json:"signing_type_id,omitempty"` // 签订类型, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name: pre_hire- custom_api_name: signing_type示例值: "new"
WorkerID *string `json:"worker_id,omitempty"` // 工号示例值: "DDD00001"
CheckInTime *string `json:"check_in_time,omitempty"` // 签到日期, 格式: "YYYY-MM-DD"示例值: "2024-12-31"
CheckInMethod *string `json:"check_in_method,omitempty"` // 签到方式, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name: pre_hire- custom_api_name: onboarding_method示例值: "onsite"
Company *string `json:"company,omitempty"` // 公司主体, 可以通过[批量查询公司](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/company/list)接口查询示例值: "6738317738688661772"
WorkShift *string `json:"work_shift,omitempty"` // 排班, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name = pre_hire- custom_api_name = work_shift示例值: "work_shift"
RecruitmentTypeID *string `json:"recruitment_type_id,omitempty"` // 招聘类型, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name = pre_hire- custom_api_name = recruitment_type示例值: "experienced_professionals"
CompensationType *string `json:"compensation_type,omitempty"` // 薪资类型, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name = pre_hire- custom_api_name = compensation_type示例值: "hourly"
PayGroupID *string `json:"pay_group_id,omitempty"` // 薪资组, 如需获取具体值, 请联系人员档案管理员示例值: "6977976687350924833"
OfferHRID *string `json:"offer_hr_id,omitempty"` // Offer HR 雇佣ID, 可以通过[批量查询员工信息](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/employee/batch_get)接口获取示例值: "7032210902531327521"
JobID *string `json:"job_id,omitempty"` // 职务 ID, 可以通过[批量查询职务](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/job/list)接口获取示例值: "6977976735715378724"
JobFamilyID *string `json:"job_family_id,omitempty"` // 序列 ID, 可以通过[批量查询序列](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/job_family/list)接口获取示例值: "6977972856625939999"
JobLevelID *string `json:"job_level_id,omitempty"` // 职级 ID, 可以通过[批量查询职级](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/job_level/list)接口获取示例值: "6977971894960145950"
JobGradeID *string `json:"job_grade_id,omitempty"` // 职等ID, 可以通过[查询职等](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/job_grade/query)接口获取示例值: "6738317738688661772"
EmployeeTypeID *string `json:"employee_type_id,omitempty"` // 人员类型 ID, 可以通过接口[批量查询人员类型](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/employee_type/list)获取示例值: "6977973225846343171"
EmployeeSubtypeID *string `json:"employee_subtype_id,omitempty"` // 人员子类型示例值: "xxx"
DirectLeaderID *string `json:"direct_leader_id,omitempty"` // 直属上级, 可以通过[批量查询员工信息](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/employee/batch_get)接口获取示例值: "7032210902531327521"
DottedLineManagerID *string `json:"dotted_line_manager_id,omitempty"` // 虚线上级, 可以通过[搜索员工信息](https://open.feishu.cn/document/server-docs/corehr-v1/employee/search)接口获取详情- 功能灰度中, 如有需求请联系[技术支持](https://applink.feishu.cn/TLJpeNdW)示例值: "xxx"
DepartmentID *string `json:"department_id,omitempty"` // 部门 ID, 可以通过[批量查询部门](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/department/batch_get)接口获取示例值: "7147562782945478177"
SocialSecurityCity *string `json:"social_security_city,omitempty"` // 社保城市ID, 可以通过[批量查询地点](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/location/list)接口获得示例值: "6977976687350924833"
WorkLocationID *string `json:"work_location_id,omitempty"` // 工作地点ID, 可以通过[批量查询地点](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/location/list)接口获得示例值: "6977976687350924833"
WorkingCalendar *string `json:"working_calendar,omitempty"` // 工作日历, 可以通过[查询日历信息](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/query)接口获得示例值: "6890452208593372141"
WorkingHoursType *string `json:"working_hours_type,omitempty"` // 工时制度, 可以通过[批量查询工时制度](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/working_hours_type/list)接口获得示例值: "6890452208593372679"
SeniorityDate *string `json:"seniority_date,omitempty"` // 司龄起算日期示例值: "2022-10-08"
SeniorityAdjustInformationList []*UpdateCorehrPreHireReqOfferInfoUpdateSeniorityAdjustInformation `json:"seniority_adjust_information_list,omitempty"` // 司龄调整信息- 功能灰度中, 如有需求请联系[技术支持](https://applink.feishu.cn/TLJpeNdW)
NoticePeriodProbationVoluntary *UpdateCorehrPreHireReqOfferInfoUpdateNoticePeriodProbationVoluntary `json:"notice_period_probation_voluntary,omitempty"` // 试用期内通知期（主动离职)- 功能灰度中, 如有需求请联系[技术支持](https://applink.feishu.cn/TLJpeNdW)示例值: xxx
NoticePeriodProbationInvoluntary *UpdateCorehrPreHireReqOfferInfoUpdateNoticePeriodProbationInvoluntary `json:"notice_period_probation_involuntary,omitempty"` // 试用期内通知期（被动离职）- 功能灰度中, 如有需求请联系[技术支持](https://applink.feishu.cn/TLJpeNdW)示例值: xxx
NoticePeriodPositiveVoluntary *UpdateCorehrPreHireReqOfferInfoUpdateNoticePeriodPositiveVoluntary `json:"notice_period_positive_voluntary,omitempty"` // 转正后通知期（主动离职）- 功能灰度中, 如有需求请联系[技术支持](https://applink.feishu.cn/TLJpeNdW)示例值: xxx
NoticePeriodPositiveInvoluntary *UpdateCorehrPreHireReqOfferInfoUpdateNoticePeriodPositiveInvoluntary `json:"notice_period_positive_involuntary,omitempty"` // 转正后通知期（被动离职）- 功能灰度中, 如有需求请联系[技术支持](https://applink.feishu.cn/TLJpeNdW)示例值: xxx
ConditionWorker *bool `json:"condition_worker,omitempty"` // 是否外部人员示例值: true
CompanySponsoredVisa *bool `json:"company_sponsored_visa,omitempty"` // 需要公司办理签证示例值: true
WeeklyWorkingHoursV2 *float64 `json:"weekly_working_hours_v2,omitempty"` // 周工作时长（单位: 小时）示例值: 8.5
WorkStation *string `json:"work_station,omitempty"` // 工位示例值: "5-1-2"
ServiceCompany *string `json:"service_company,omitempty"` // 任职公司, 可以通过[批量查询公司](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/company/list)接口查询示例值: "6738317738688661772"
NonCompeteCovenant *bool `json:"non_compete_covenant,omitempty"` // 是否包含竞业条款示例值: true
Pathway *string `json:"pathway,omitempty"` // 通道示例值: "7460865381179115052"
DefaultCostCenter *UpdateCorehrPreHireReqOfferInfoUpdateDefaultCostCenter `json:"default_cost_center,omitempty"` // 默认成本中心- 功能灰度中, 如有需求请联系[技术支持](https://applink.feishu.cn/TLJpeNdW)
CostAllocation *UpdateCorehrPreHireReqOfferInfoUpdateCostAllocation `json:"cost_allocation,omitempty"` // 成本分摊- 功能灰度中, 如有需求请联系[技术支持](https://applink.feishu.cn/TLJpeNdW)
ReuseFeishuAccount *string `json:"reuse_feishu_account,omitempty"` // 是否复用飞书账号, 支持传入“reuse”或者“not_resue”, 当字段为“reuse”时, 需要传入reused_feishu_account_id- 功能灰度中, 如有需求请联系[技术支持](https://applink.feishu.cn/TLJpeNdW)示例值: "reuse"
ReusedFeishuAccountID *string `json:"reused_feishu_account_id,omitempty"` // 复用的飞书账号, 仅支持Lark Union ID, 可以通过[搜索员工信息](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/directory-v1/employee/search)接口获取- 功能灰度中, 如有需求请联系[技术支持](https://applink.feishu.cn/TLJpeNdW)示例值: "on_773dd2c4d14c5c980a4d89a2da5c86d3"
}





// UpdateCorehrPreHireReqOfferInfoUpdateCostAllocation ...
type UpdateCorehrPreHireReqOfferInfoUpdateCostAllocation struct { 
EffectiveTime *string `json:"effective_time,omitempty"` // 分摊生效日期示例值: "2025-01-01"
ExpirationTime *string `json:"expiration_time,omitempty"` // 分摊失效日期示例值: "2025-02-01"
CostCenterRates []*UpdateCorehrPreHireReqOfferInfoUpdateCostAllocationCostCenterRate `json:"cost_center_rates,omitempty"` // 成本分摊信息 长度范围: `0` ～ `50`
}





// UpdateCorehrPreHireReqOfferInfoUpdateCostAllocationCostCenterRate ...
type UpdateCorehrPreHireReqOfferInfoUpdateCostAllocationCostCenterRate struct { 
CostCenterID *string `json:"cost_center_id,omitempty"` // 成本中心 ID, 可以通过[搜索成本中心信息](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/cost_center/search)接口获得示例值: "6950635856373745165"
Rate *int64 `json:"rate,omitempty"` // 分摊比例(整数)示例值: 100
NewRate *float64 `json:"new_rate,omitempty"` // 分摊比例示例值: 50.2
}





// UpdateCorehrPreHireReqOfferInfoUpdateCostCenterRate ...
type UpdateCorehrPreHireReqOfferInfoUpdateCostCenterRate struct { 
CostCenterID *string `json:"cost_center_id,omitempty"` // 成本中心 ID, 可以通过[搜索成本中心信息](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/cost_center/search)接口获得示例值: "6950635856373745165"
Rate *int64 `json:"rate,omitempty"` // 分摊比例, 大于0小于等于100的正整数示例值: 100
NewRate *float64 `json:"new_rate,omitempty"` // 分摊比例示例值: 50.2
}





// UpdateCorehrPreHireReqOfferInfoUpdateCustomField ...
type UpdateCorehrPreHireReqOfferInfoUpdateCustomField struct { 
FieldName string `json:"field_name,omitempty"` // 字段名示例值: "name"
Value string `json:"value,omitempty"` // 字段值, 该值是一个 string list 经转义后的字符串, 具体参考请求体示例示例值: "[\"Sandy\"]"
}





// UpdateCorehrPreHireReqOfferInfoUpdateDefaultCostCenter ...
type UpdateCorehrPreHireReqOfferInfoUpdateDefaultCostCenter struct { 
CostCenterID string `json:"cost_center_id,omitempty"` // 成本中心 ID, 可以通过[搜索成本中心信息](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/cost_center/search)接口获得示例值: "6950635856373745165"
IsHerit bool `json:"is_herit,omitempty"` // 是否继承岗位/部门的默认成本中心示例值: false
}





// UpdateCorehrPreHireReqOfferInfoUpdateNoticePeriodPositiveInvoluntary ...
type UpdateCorehrPreHireReqOfferInfoUpdateNoticePeriodPositiveInvoluntary struct { 
WkID *string `json:"wk_id,omitempty"` // ID示例值: "4698019107896524633"
Value *int64 `json:"value,omitempty"` // 数值示例值: 1 取值范围: `1` ～ `65535`
ValueUnit *string `json:"value_unit,omitempty"` // 单位示例值: "月"
}





// UpdateCorehrPreHireReqOfferInfoUpdateNoticePeriodPositiveVoluntary ...
type UpdateCorehrPreHireReqOfferInfoUpdateNoticePeriodPositiveVoluntary struct { 
WkID *string `json:"wk_id,omitempty"` // ID示例值: "4698019107896524633"
Value *int64 `json:"value,omitempty"` // 数值示例值: 1 取值范围: `1` ～ `65535`
ValueUnit *string `json:"value_unit,omitempty"` // 单位示例值: "月"
}





// UpdateCorehrPreHireReqOfferInfoUpdateNoticePeriodProbationInvoluntary ...
type UpdateCorehrPreHireReqOfferInfoUpdateNoticePeriodProbationInvoluntary struct { 
WkID *string `json:"wk_id,omitempty"` // ID示例值: "4698019107896524633"
Value *int64 `json:"value,omitempty"` // 数值示例值: 1 取值范围: `1` ～ `65535`
ValueUnit *string `json:"value_unit,omitempty"` // 单位示例值: "月"
}





// UpdateCorehrPreHireReqOfferInfoUpdateNoticePeriodProbationVoluntary ...
type UpdateCorehrPreHireReqOfferInfoUpdateNoticePeriodProbationVoluntary struct { 
WkID *string `json:"wk_id,omitempty"` // ID示例值: "4698019107896524633"
Value *int64 `json:"value,omitempty"` // 数值示例值: 1 取值范围: `1` ～ `65535`
ValueUnit *string `json:"value_unit,omitempty"` // 单位示例值: "月"
}





// UpdateCorehrPreHireReqOfferInfoUpdateSeniorityAdjustInformation ...
type UpdateCorehrPreHireReqOfferInfoUpdateSeniorityAdjustInformation struct { 
SeniorityAdjustment *float64 `json:"seniority_adjustment,omitempty"` // 调整值- 精确度: 两位小数- 单位: 年- 自动计算逻辑: 如果这个值为空, 司龄调整的开始日期和结束日期均不为空, 会自动计算出调整值示例值: 0.5 取值范围: `0` ～ `100`
SeniorityAdjustmentType string `json:"seniority_adjustment_type,omitempty"` // 调整类型- 可通过[【获取字段详情】](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口查询, 查询参数如下: - object_api_name: seniority_adjust_information  - custom_api_name: seniority_adjustment_type示例值: "增加"可选值有: 减少增加
ReasonsForSeniorityAdjustment *string `json:"reasons_for_seniority_adjustment,omitempty"` // 司龄调整原因示例值: "工厂停产需要减去半年工龄"
StartDate *string `json:"start_date,omitempty"` // 开始日期- 格式: yyyy-mm-dd示例值: "2024-05-19"
EndDate *string `json:"end_date,omitempty"` // 结束日期- 格式: yyyy-mm-dd示例值: "2024-11-18"
CustomFields []*UpdateCorehrPreHireReqOfferInfoUpdateSeniorityAdjustInformationCustomField `json:"custom_fields,omitempty"` // 自定义字段
}





// UpdateCorehrPreHireReqOfferInfoUpdateSeniorityAdjustInformationCustomField ...
type UpdateCorehrPreHireReqOfferInfoUpdateSeniorityAdjustInformationCustomField struct { 
FieldName string `json:"field_name,omitempty"` // 字段名示例值: "name"
Value string `json:"value,omitempty"` // 字段值, 是json转义后的字符串, 根据元数据定义不同, 字段格式不同(123, 123.23, true, [\"id1\", \"id2\], 2006-01-02 15:04:05])示例值: "Sandy"
}





// UpdateCorehrPreHireReqOfferInfoUpdateWorkEmail ...
type UpdateCorehrPreHireReqOfferInfoUpdateWorkEmail struct { 
Email string `json:"email,omitempty"` // 邮箱地址示例值: "1234567@bytedance.com"
IsPrimary bool `json:"is_primary,omitempty"` // 是否为主要邮箱, 若有多个邮箱, 只能有一个邮箱的「is_primary」为true示例值: true
IsPublic bool `json:"is_public,omitempty"` // 是否为公开邮箱示例值: true
EmailUsage string `json:"email_usage,omitempty"` // 邮箱用途, 枚举值可查询[获取字段详情](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/custom_field/get_by_param)接口获取, 按如下参数查询即可: object_api_name = email- custom_api_name = email_usage示例值: "work"
}





// UpdateCorehrPreHireResp ...
type UpdateCorehrPreHireResp struct { 
PreHireID string `json:"pre_hire_id,omitempty"` // 待入职ID
}





// updateCorehrPreHireResp ...
type updateCorehrPreHireResp struct { 
Code int64 `json:"code,omitempty"` // 错误码, 非 0 表示失败
Msg string `json:"msg,omitempty"` // 错误描述
Data *UpdateCorehrPreHireResp `json:"data,omitempty"` 
Error *ErrorDetail `json:"error,omitempty"` 
}




