// Code generated by lark_sdk_gen. DO NOT EDIT.
/**
 * Copyright 2022 chyroc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package lark

import (
"context"
)

// CreateVCMeetingDefaultBuildingCreate 该接口对应管理后台的添加建筑, 添加楼层的功能, 可用于创建建筑物和建筑物的楼层信息。
//
// doc: https://open.feishu.cn/document/ukTMukTMukTM/uATNwYjLwUDM24CM1AjN
// 
func (r *VCMeetingService) CreateVCMeetingDefaultBuildingCreate(ctx context.Context, request *CreateVCMeetingDefaultBuildingCreateReq, options ...MethodOptionFunc) (*CreateVCMeetingDefaultBuildingCreateResp, *Response, error) {
if r.cli.mock.mockVCMeetingCreateVCMeetingDefaultBuildingCreate != nil {
		r.cli.Log(ctx, LogLevelDebug, "[lark] VCMeeting#CreateVCMeetingDefaultBuildingCreate mock enable")
		return r.cli.mock.mockVCMeetingCreateVCMeetingDefaultBuildingCreate(ctx, request, options...)
	}

	req := &RawRequestReq{
		Scope:                 "VCMeeting",
		API:                   "CreateVCMeetingDefaultBuildingCreate",
		Method:                "POST",
		URL:   r.cli.openBaseURL + "/open-apis/meeting_room/building/create",
		Body:                  request,
		MethodOption:          newMethodOption(options),
 NeedTenantAccessToken: true,

	}
	resp := new(createVCMeetingDefaultBuildingCreateResp)

	response, err := r.cli.RawRequest(ctx, req, resp)
	return resp.Data, response, err
}

// MockVCMeetingCreateVCMeetingDefaultBuildingCreate mock VCMeetingCreateVCMeetingDefaultBuildingCreate method
func (r *Mock) MockVCMeetingCreateVCMeetingDefaultBuildingCreate(f func(ctx context.Context, request *CreateVCMeetingDefaultBuildingCreateReq, options ...MethodOptionFunc) (*CreateVCMeetingDefaultBuildingCreateResp, *Response, error)) {
	r.mockVCMeetingCreateVCMeetingDefaultBuildingCreate = f
}
// UnMockVCMeetingCreateVCMeetingDefaultBuildingCreate un-mock VCMeetingCreateVCMeetingDefaultBuildingCreate method
func (r *Mock) UnMockVCMeetingCreateVCMeetingDefaultBuildingCreate() {
	r.mockVCMeetingCreateVCMeetingDefaultBuildingCreate = nil
}


// CreateVCMeetingDefaultBuildingCreateReq ...
type CreateVCMeetingDefaultBuildingCreateReq struct { 
Name string `json:"name,omitempty"` // 建筑名称
Floors []string `json:"floors,omitempty"` // 楼层列表
CountryID string `json:"country_id,omitempty"` // 国家/地区ID
DistrictID string `json:"district_id,omitempty"` // 城市ID
CustomBuildingID *string `json:"custom_building_id,omitempty"` // 租户自定义建筑ID
}





// CreateVCMeetingDefaultBuildingCreateResp ...
type CreateVCMeetingDefaultBuildingCreateResp struct { 
BuildingID string `json:"building_id,omitempty"` // 成功创建的建筑ID
}





// createVCMeetingDefaultBuildingCreateResp ...
type createVCMeetingDefaultBuildingCreateResp struct { 
Code int64 `json:"code,omitempty"` // 返回码, 非 0 表示失败
Msg string `json:"msg,omitempty"` // 返回码的描述, "success" 表示成功, 其他为错误提示信息
Data *CreateVCMeetingDefaultBuildingCreateResp `json:"data,omitempty"` // 返回业务信息
Error *ErrorDetail `json:"error,omitempty"` 
}




