// Code generated by lark_sdk_gen. DO NOT EDIT.

package lark

import (
	"context"
)

// GetUserStatisticsSettings
//
// doc: https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/Attendance//task/query-user-statistics-settings
func (r *AttendanceAPI) GetUserStatisticsSettings(ctx context.Context, request *GetUserStatisticsSettingsReq, options ...MethodOptionFunc) (*GetUserStatisticsSettingsResp, *Response, error) {
	r.cli.logInfo(ctx, "[lark] Attendance#GetUserStatisticsSettings call api")
	r.cli.logDebug(ctx, "[lark] Attendance#GetUserStatisticsSettings request: %s", jsonString(request))

	if r.cli.mock.mockAttendanceGetUserStatisticsSettings != nil {
		r.cli.logDebug(ctx, "[lark] Attendance#GetUserStatisticsSettings mock enable")
		return r.cli.mock.mockAttendanceGetUserStatisticsSettings(ctx, request, options...)
	}

	req := &RawRequestReq{
		Method:                "POST",
		URL:                   "https://open.feishu.cn/open-apis/attendance/v1/user_stats_views/query",
		Body:                  request,
		MethodOption:          newMethodOption(options),
		NeedTenantAccessToken: true,
	}
	resp := new(getUserStatisticsSettingsResp)

	response, err := r.cli.RawRequest(ctx, req, resp)
	if err != nil {
		r.cli.logError(ctx, "[lark] Attendance#GetUserStatisticsSettings POST https://open.feishu.cn/open-apis/attendance/v1/user_stats_views/query failed: %s", err)
		return nil, response, err
	} else if resp.Code != 0 {
		r.cli.logError(ctx, "[lark] Attendance#GetUserStatisticsSettings POST https://open.feishu.cn/open-apis/attendance/v1/user_stats_views/query failed, code: %d, msg: %s", resp.Code, resp.Msg)
		return nil, response, NewError("Attendance", "GetUserStatisticsSettings", resp.Code, resp.Msg)
	}

	r.cli.logDebug(ctx, "[lark] Attendance#GetUserStatisticsSettings request_id: %s, response: %s", response.RequestID, jsonString(resp.Data))

	return resp.Data, response, nil
}

func (r *Mock) MockAttendanceGetUserStatisticsSettings(f func(ctx context.Context, request *GetUserStatisticsSettingsReq, options ...MethodOptionFunc) (*GetUserStatisticsSettingsResp, *Response, error)) {
	r.mockAttendanceGetUserStatisticsSettings = f
}

func (r *Mock) UnMockAttendanceGetUserStatisticsSettings() {
	r.mockAttendanceGetUserStatisticsSettings = nil
}

type GetUserStatisticsSettingsReq struct {
	EmployeeType EmployeeType `query:"employee_type" json:"-"` // 用户 ID 类型, 可选值有: `employee_id`, `employee_no`
	Locale       string       `json:"locale,omitempty"`        // 语言类型, 可选值有: `en`：英文, `ja`：日文, `zh`：中文
	StatsType    string       `json:"stats_type,omitempty"`    // 统计类型,      , 可选值有: `daily`：日度统计, `month`：月度统计
}

type getUserStatisticsSettingsResp struct {
	Code int                            `json:"code,omitempty"` // 错误码，非 0 表示失败
	Msg  string                         `json:"msg,omitempty"`  // 错误描述
	Data *GetUserStatisticsSettingsResp `json:"data,omitempty"` //
}

type GetUserStatisticsSettingsResp struct {
	View *GetUserStatisticsSettingsRespView `json:"view,omitempty"` // 统计视图
}

type GetUserStatisticsSettingsRespView struct {
	ViewID    string                                   `json:"view_id,omitempty"`    // 视图 ID
	StatsType string                                   `json:"stats_type,omitempty"` // 统计类型, 可选值有: `daily`：日度统计, `month`：月度统计
	UserID    string                                   `json:"user_id,omitempty"`    // 用户 ID
	Items     []*GetUserStatisticsSettingsRespViewItem `json:"items,omitempty"`      // 一级标题
}

type GetUserStatisticsSettingsRespViewItem struct {
	Code       int                                               `json:"code,omitempty"`        // 标题编号
	Title      string                                            `json:"title,omitempty"`       // 标题名称
	ChildItems []*GetUserStatisticsSettingsRespViewItemChildItem `json:"child_items,omitempty"` // 子标题
}

type GetUserStatisticsSettingsRespViewItemChildItem struct {
	Code       int    `json:"code,omitempty"`        // 标题编号
	Value      string `json:"value,omitempty"`       // 是否开启,      , 可选值有: `0`：关闭, `1`：开启
	Title      string `json:"title,omitempty"`       // 标题名称
	ColumnType int    `json:"column_type,omitempty"` // 标题类型
	ReadOnly   bool   `json:"read_only,omitempty"`   // 是否只读
	MinValue   string `json:"min_value,omitempty"`   // 最小值
	MaxValue   string `json:"max_value,omitempty"`   // 最大值
}
