// Code generated by lark_sdk_gen. DO NOT EDIT.

package lark

import (
	"context"
)

// UpdateUserSettings
//
// doc: https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/Attendance//rule/user-setting-modify
func (r *AttendanceService) UpdateUserSettings(ctx context.Context, request *UpdateUserSettingsReq, options ...MethodOptionFunc) (*UpdateUserSettingsResp, *Response, error) {
	if r.cli.mock.mockAttendanceUpdateUserSettings != nil {
		r.cli.log(ctx, LogLevelDebug, "[lark] Attendance#UpdateUserSettings mock enable")
		return r.cli.mock.mockAttendanceUpdateUserSettings(ctx, request, options...)
	}

	req := &RawRequestReq{
		Scope:                 "Attendance",
		API:                   "UpdateUserSettings",
		Method:                "POST",
		URL:                   "https://open.feishu.cn/open-apis/attendance/v1/user_settings/modify",
		Body:                  request,
		MethodOption:          newMethodOption(options),
		NeedTenantAccessToken: true,
	}
	resp := new(updateUserSettingsResp)

	response, err := r.cli.RawRequest(ctx, req, resp)
	return resp.Data, response, err
}

func (r *Mock) MockAttendanceUpdateUserSettings(f func(ctx context.Context, request *UpdateUserSettingsReq, options ...MethodOptionFunc) (*UpdateUserSettingsResp, *Response, error)) {
	r.mockAttendanceUpdateUserSettings = f
}

func (r *Mock) UnMockAttendanceUpdateUserSettings() {
	r.mockAttendanceUpdateUserSettings = nil
}

type UpdateUserSettingsReq struct {
	EmployeeType EmployeeType                      `query:"employee_type" json:"-"` // 用户类型, 可选值有: `employee_id`： 员工id, `employee_no`： 员工工号
	UserSetting  *UpdateUserSettingsReqUserSetting `json:"user_setting,omitempty"`  // 用户信息
}

type UpdateUserSettingsReqUserSetting struct {
	UserID  string `json:"user_id,omitempty"`  // 用户id
	FaceKey string `json:"face_key,omitempty"` // 人脸照片key（通过文件上传接口得到）
}

type updateUserSettingsResp struct {
	Code int64                   `json:"code,omitempty"` // 错误码，非 0 表示失败
	Msg  string                  `json:"msg,omitempty"`  // 错误描述
	Data *UpdateUserSettingsResp `json:"data,omitempty"` //
}

type UpdateUserSettingsResp struct {
	UserSetting *UpdateUserSettingsRespUserSetting `json:"user_setting,omitempty"` // 用户设置
}

type UpdateUserSettingsRespUserSetting struct {
	UserID  string `json:"user_id,omitempty"`  // 用户id
	FaceKey string `json:"face_key,omitempty"` // 人脸照片key
}
