// Code generated by lark_sdk_gen. DO NOT EDIT.
/**
 * Copyright 2022 chyroc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package lark

import (
	"context"
)

// DeleteHireNote 根据备注 ID 删除备注。
//
// doc: https://open.feishu.cn/document/ukTMukTMukTM/uMzM1YjLzMTN24yMzUjN/hire-v1/note/delete
// new doc: https://open.feishu.cn/document/hire-v1/candidate-management/note/delete
func (r *HireService) DeleteHireNote(ctx context.Context, request *DeleteHireNoteReq, options ...MethodOptionFunc) (*DeleteHireNoteResp, *Response, error) {
	if r.cli.mock.mockHireDeleteHireNote != nil {
		r.cli.Log(ctx, LogLevelDebug, "[lark] Hire#DeleteHireNote mock enable")
		return r.cli.mock.mockHireDeleteHireNote(ctx, request, options...)
	}

	req := &RawRequestReq{
		Scope:                 "Hire",
		API:                   "DeleteHireNote",
		Method:                "DELETE",
		URL:                   r.cli.openBaseURL + "/open-apis/hire/v1/notes/:note_id",
		Body:                  request,
		MethodOption:          newMethodOption(options),
		NeedTenantAccessToken: true,
	}
	resp := new(deleteHireNoteResp)

	response, err := r.cli.RawRequest(ctx, req, resp)
	return resp.Data, response, err
}

// MockHireDeleteHireNote mock HireDeleteHireNote method
func (r *Mock) MockHireDeleteHireNote(f func(ctx context.Context, request *DeleteHireNoteReq, options ...MethodOptionFunc) (*DeleteHireNoteResp, *Response, error)) {
	r.mockHireDeleteHireNote = f
}

// UnMockHireDeleteHireNote un-mock HireDeleteHireNote method
func (r *Mock) UnMockHireDeleteHireNote() {
	r.mockHireDeleteHireNote = nil
}

// DeleteHireNoteReq ...
type DeleteHireNoteReq struct {
	NoteID string `path:"note_id" json:"-"` // 备注 ID, 可通过[获取备注列表](https://open.feishu.cn/document/ukTMukTMukTM/uMzM1YjLzMTN24yMzUjN/hire-v1/note/list)获取示例值: "6996605821056812588"
}

// DeleteHireNoteResp ...
type DeleteHireNoteResp struct {
}

// deleteHireNoteResp ...
type deleteHireNoteResp struct {
	Code  int64               `json:"code,omitempty"` // 错误码, 非 0 表示失败
	Msg   string              `json:"msg,omitempty"`  // 错误描述
	Data  *DeleteHireNoteResp `json:"data,omitempty"`
	Error *ErrorDetail        `json:"error,omitempty"`
}
