// Code generated by lark_sdk_gen. DO NOT EDIT.
/**
 * Copyright 2022 chyroc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package lark

import (
	"context"
)

// EventV1P2PChatCreate 应用机器人订阅该事件后, 如果用户首次与该机器人进行会话, 将会触发该事件。首次会话是用户了解应用的重要机会, 你可以在触发事件后, 向用户发送操作说明、配置地址来指导用户开始使用你的应用。
//
// ## 前提条件
// 你需要先为应用配置事件订阅, 才可以在触发事件时接收到事件。事件订阅介绍参见[事件概述](https://open.feishu.cn/document/ukTMukTMukTM/uUTNz4SN1MjL1UzM)。
//
// doc: https://open.feishu.cn/document/ukTMukTMukTM/uYDNxYjL2QTM24iN0EjN/bot-events
// new doc: https://open.feishu.cn/document/server-docs/group/chat-member/event/bot-events
func (r *EventCallbackService) HandlerEventV1P2PChatCreate(f EventV1P2PChatCreateHandler) {
	r.cli.eventHandler.eventV1P2PChatCreateHandler = f
}

// EventV1P2PChatCreateHandler event EventV1P2PChatCreate handler
type EventV1P2PChatCreateHandler func(ctx context.Context, cli *Lark, schema string, header *EventHeaderV1, event *EventV1P2PChatCreate) (string, error)

// EventV1P2PChatCreate ...
type EventV1P2PChatCreate struct {
}

// EventV1P2PChatCreateResp ...
type EventV1P2PChatCreateResp struct {
}

// eventV1P2PChatCreateResp ...
type eventV1P2PChatCreateResp struct {
	Code  int64                     `json:"code,omitempty"`
	Msg   string                    `json:"msg,omitempty"`
	Data  *EventV1P2PChatCreateResp `json:"data,omitempty"`
	Error *ErrorDetail              `json:"error,omitempty"`
}
