// Code generated by lark_sdk_gen. DO NOT EDIT.
/**
 * Copyright 2022 chyroc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package lark

import (
	"context"
)

// EventV2ContactEmployeeTypeEnumUpdatedV3 当应用订阅该事件后, 若果更新了人员类型的选项内容（包括默认内容 content 参数和国际化内容 i18n_content）, 则会触发该事件。{使用示例}(url=/api/tools/api_explore/api_explore_config?project=contact&version=v3&resource=employee_type_enum&event=updated)
//
// ## 前提条件
// 你需要在应用中配置事件订阅, 这样才可以在事件触发时接收到事件数据。了解事件订阅可参见[事件订阅概述](https://open.feishu.cn/document/ukTMukTMukTM/uUTNz4SN1MjL1UzM)。
//
// doc: https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/contact-v3/employee_type_enum/events/updated
// new doc: https://open.feishu.cn/document/server-docs/contact-v3/employee_type_enum/events/updated
func (r *EventCallbackService) HandlerEventV2ContactEmployeeTypeEnumUpdatedV3(f EventV2ContactEmployeeTypeEnumUpdatedV3Handler) {
	r.cli.eventHandler.eventV2ContactEmployeeTypeEnumUpdatedV3Handler = f
}

// EventV2ContactEmployeeTypeEnumUpdatedV3Handler event EventV2ContactEmployeeTypeEnumUpdatedV3 handler
type EventV2ContactEmployeeTypeEnumUpdatedV3Handler func(ctx context.Context, cli *Lark, schema string, header *EventHeaderV2, event *EventV2ContactEmployeeTypeEnumUpdatedV3) (string, error)

// EventV2ContactEmployeeTypeEnumUpdatedV3 ...
type EventV2ContactEmployeeTypeEnumUpdatedV3 struct {
	OldEnum *EventV2ContactEmployeeTypeEnumUpdatedV3OldEnum `json:"old_enum,omitempty"` // 更新前的人员类型信息。
	NewEnum *EventV2ContactEmployeeTypeEnumUpdatedV3NewEnum `json:"new_enum,omitempty"` // 更新后的人员类型信息。
}

// EventV2ContactEmployeeTypeEnumUpdatedV3NewEnum ...
type EventV2ContactEmployeeTypeEnumUpdatedV3NewEnum struct {
	EnumID      string                                                       `json:"enum_id,omitempty"`      // 人员类型的选项 ID。
	EnumValue   string                                                       `json:"enum_value,omitempty"`   // 人员类型的选项编号。
	Content     string                                                       `json:"content,omitempty"`      // 人员类型的选项内容。 长度范围: `1` ～ `100` 字符
	EnumType    int64                                                        `json:"enum_type,omitempty"`    // 人员类型的选项类型。可选值有: 内置类型自定义
	EnumStatus  int64                                                        `json:"enum_status,omitempty"`  // 人员类型的选项激活状态。可选值有: 激活未激活
	I18nContent []*EventV2ContactEmployeeTypeEnumUpdatedV3NewEnumI18nContent `json:"i18n_content,omitempty"` // 选项内容的国际化配置。
}

// EventV2ContactEmployeeTypeEnumUpdatedV3NewEnumI18nContent ...
type EventV2ContactEmployeeTypeEnumUpdatedV3NewEnumI18nContent struct {
	Locale string `json:"locale,omitempty"` // 语言版本。例如: zh_cn: 中文- en_us: 英文- ja_jp: 日文
	Value  string `json:"value,omitempty"`  // 语言版本对应的内容。
}

// EventV2ContactEmployeeTypeEnumUpdatedV3OldEnum ...
type EventV2ContactEmployeeTypeEnumUpdatedV3OldEnum struct {
	EnumID      string                                                       `json:"enum_id,omitempty"`      // 人员类型的选项 ID。
	EnumValue   string                                                       `json:"enum_value,omitempty"`   // 人员类型的选项编号。
	Content     string                                                       `json:"content,omitempty"`      // 人员类型的选项内容。 长度范围: `1` ～ `100` 字符
	EnumType    int64                                                        `json:"enum_type,omitempty"`    // 人员类型的选项类型。可选值有: 内置类型自定义
	EnumStatus  int64                                                        `json:"enum_status,omitempty"`  // 人员类型的选项激活状态。可选值有: 激活未激活
	I18nContent []*EventV2ContactEmployeeTypeEnumUpdatedV3OldEnumI18nContent `json:"i18n_content,omitempty"` // 选项内容的国际化配置。
}

// EventV2ContactEmployeeTypeEnumUpdatedV3OldEnumI18nContent ...
type EventV2ContactEmployeeTypeEnumUpdatedV3OldEnumI18nContent struct {
	Locale string `json:"locale,omitempty"` // 语言版本。例如: zh_cn: 中文- en_us: 英文- ja_jp: 日文
	Value  string `json:"value,omitempty"`  // 语言版本对应的内容。
}

// EventV2ContactEmployeeTypeEnumUpdatedV3Resp ...
type EventV2ContactEmployeeTypeEnumUpdatedV3Resp struct {
}

// eventV2ContactEmployeeTypeEnumUpdatedV3Resp ...
type eventV2ContactEmployeeTypeEnumUpdatedV3Resp struct {
	Code  int64                                        `json:"code,omitempty"`
	Msg   string                                       `json:"msg,omitempty"`
	Data  *EventV2ContactEmployeeTypeEnumUpdatedV3Resp `json:"data,omitempty"`
	Error *ErrorDetail                                 `json:"error,omitempty"`
}
