// Code generated by lark_sdk_gen. DO NOT EDIT.
/**
 * Copyright 2022 chyroc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package lark

import (
	"context"
)

// CreateAPaaSUserTaskRollback 对当前任务进行一次退回
//
// doc: https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/apaas-v1/user_task/rollback
// new doc: https://open.feishu.cn/document/apaas-v1/flow/user-task/rollback
func (r *APaaSService) CreateAPaaSUserTaskRollback(ctx context.Context, request *CreateAPaaSUserTaskRollbackReq, options ...MethodOptionFunc) (*CreateAPaaSUserTaskRollbackResp, *Response, error) {
	if r.cli.mock.mockAPaaSCreateAPaaSUserTaskRollback != nil {
		r.cli.Log(ctx, LogLevelDebug, "[lark] APaaS#CreateAPaaSUserTaskRollback mock enable")
		return r.cli.mock.mockAPaaSCreateAPaaSUserTaskRollback(ctx, request, options...)
	}

	req := &RawRequestReq{
		Scope:                 "APaaS",
		API:                   "CreateAPaaSUserTaskRollback",
		Method:                "POST",
		URL:                   r.cli.openBaseURL + "/open-apis/apaas/v1/user_tasks/:task_id/rollback",
		Body:                  request,
		MethodOption:          newMethodOption(options),
		NeedTenantAccessToken: true,
	}
	resp := new(createAPaaSUserTaskRollbackResp)

	response, err := r.cli.RawRequest(ctx, req, resp)
	return resp.Data, response, err
}

// MockAPaaSCreateAPaaSUserTaskRollback mock APaaSCreateAPaaSUserTaskRollback method
func (r *Mock) MockAPaaSCreateAPaaSUserTaskRollback(f func(ctx context.Context, request *CreateAPaaSUserTaskRollbackReq, options ...MethodOptionFunc) (*CreateAPaaSUserTaskRollbackResp, *Response, error)) {
	r.mockAPaaSCreateAPaaSUserTaskRollback = f
}

// UnMockAPaaSCreateAPaaSUserTaskRollback un-mock APaaSCreateAPaaSUserTaskRollback method
func (r *Mock) UnMockAPaaSCreateAPaaSUserTaskRollback() {
	r.mockAPaaSCreateAPaaSUserTaskRollback = nil
}

// CreateAPaaSUserTaskRollbackReq ...
type CreateAPaaSUserTaskRollbackReq struct {
	TaskID         string `path:"task_id" json:"-"`           // 任务ID, 可以通过[查询人工任务](/uAjLw4CM/ukTMukTMukTM/apaas-v1/user_task/query)获取示例值: "1234"
	OperatorUserID string `json:"operator_user_id,omitempty"` // 操作人kunlunUserID, 可通过Apaas用户管理页面获取示例值: "1234"
	ToTaskID       string `json:"to_task_id,omitempty"`       // 退回到的任务ID, 可以通过[查询人工任务可退回的点](/uAjLw4CM/ukTMukTMukTM/apaas-v1/user_task/rollback_points)获取示例值: "1234"
	Opinion        string `json:"opinion,omitempty"`          // 退回原因示例值: "退回原因"
}

// CreateAPaaSUserTaskRollbackResp ...
type CreateAPaaSUserTaskRollbackResp struct {
}

// createAPaaSUserTaskRollbackResp ...
type createAPaaSUserTaskRollbackResp struct {
	Code  int64                            `json:"code,omitempty"` // 错误码, 非 0 表示失败
	Msg   string                           `json:"msg,omitempty"`  // 错误描述
	Data  *CreateAPaaSUserTaskRollbackResp `json:"data,omitempty"`
	Error *ErrorDetail                     `json:"error,omitempty"`
}
