// Code generated by lark_sdk_gen. DO NOT EDIT.
/**
 * Copyright 2022 chyroc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package lark

import (
	"context"
)

// UpdateVCMeetingDefaultRoom 该接口用于更新会议室。
//
// doc: https://open.feishu.cn/document/ukTMukTMukTM/uMTNwYjLzUDM24yM1AjN
// new doc: https://open.feishu.cn/document/server-docs/historic-version/meeting_room-v1/api-reference/update-meeting-room
//
// Deprecated
func (r *VCService) UpdateVCMeetingDefaultRoom(ctx context.Context, request *UpdateVCMeetingDefaultRoomReq, options ...MethodOptionFunc) (*UpdateVCMeetingDefaultRoomResp, *Response, error) {
	if r.cli.mock.mockVCUpdateVCMeetingDefaultRoom != nil {
		r.cli.Log(ctx, LogLevelDebug, "[lark] VC#UpdateVCMeetingDefaultRoom mock enable")
		return r.cli.mock.mockVCUpdateVCMeetingDefaultRoom(ctx, request, options...)
	}

	req := &RawRequestReq{
		Scope:                 "VC",
		API:                   "UpdateVCMeetingDefaultRoom",
		Method:                "POST",
		URL:                   r.cli.openBaseURL + "/open-apis/meeting_room/room/update",
		Body:                  request,
		MethodOption:          newMethodOption(options),
		NeedTenantAccessToken: true,
	}
	resp := new(updateVCMeetingDefaultRoomResp)

	response, err := r.cli.RawRequest(ctx, req, resp)
	return resp.Data, response, err
}

// MockVCUpdateVCMeetingDefaultRoom mock VCUpdateVCMeetingDefaultRoom method
func (r *Mock) MockVCUpdateVCMeetingDefaultRoom(f func(ctx context.Context, request *UpdateVCMeetingDefaultRoomReq, options ...MethodOptionFunc) (*UpdateVCMeetingDefaultRoomResp, *Response, error)) {
	r.mockVCUpdateVCMeetingDefaultRoom = f
}

// UnMockVCUpdateVCMeetingDefaultRoom un-mock VCUpdateVCMeetingDefaultRoom method
func (r *Mock) UnMockVCUpdateVCMeetingDefaultRoom() {
	r.mockVCUpdateVCMeetingDefaultRoom = nil
}

// UpdateVCMeetingDefaultRoomReq ...
type UpdateVCMeetingDefaultRoomReq struct {
	RoomID       string  `json:"room_id,omitempty"`        // 要更新的会议室ID
	Name         *string `json:"name,omitempty"`           // 会议室名称
	Capacity     *int64  `json:"capacity,omitempty"`       // 容量
	CustomRoomID *string `json:"custom_room_id,omitempty"` // 租户自定义会议室ID
}

// UpdateVCMeetingDefaultRoomResp ...
type UpdateVCMeetingDefaultRoomResp struct {
}

// updateVCMeetingDefaultRoomResp ...
type updateVCMeetingDefaultRoomResp struct {
	Code  int64                           `json:"code,omitempty"` // 返回码, 非 0 表示失败
	Msg   string                          `json:"msg,omitempty"`  // 返回码的描述, "success" 表示成功, 其他为错误提示信息
	Data  *UpdateVCMeetingDefaultRoomResp `json:"data,omitempty"`
	Error *ErrorDetail                    `json:"error,omitempty"`
}
