// Code generated by lark_sdk_gen. DO NOT EDIT.
/**
 * Copyright 2022 chyroc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package lark

import (
	"context"
)

// GetAPaaSWorkspaceEnumGet 获取自定义枚举详细信息
//
// doc: https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/apaas-v1/workspace-enum/enum_get
func (r *APaaSService) GetAPaaSWorkspaceEnumGet(ctx context.Context, request *GetAPaaSWorkspaceEnumGetReq, options ...MethodOptionFunc) (*GetAPaaSWorkspaceEnumGetResp, *Response, error) {
	if r.cli.mock.mockAPaaSGetAPaaSWorkspaceEnumGet != nil {
		r.cli.Log(ctx, LogLevelDebug, "[lark] APaaS#GetAPaaSWorkspaceEnumGet mock enable")
		return r.cli.mock.mockAPaaSGetAPaaSWorkspaceEnumGet(ctx, request, options...)
	}

	req := &RawRequestReq{
		Scope:               "APaaS",
		API:                 "GetAPaaSWorkspaceEnumGet",
		Method:              "GET",
		URL:                 r.cli.openBaseURL + "/open-apis/apaas/v1/workspaces/:workspace_id/enums/:enum_name",
		Body:                request,
		MethodOption:        newMethodOption(options),
		NeedUserAccessToken: true,
	}
	resp := new(getAPaaSWorkspaceEnumGetResp)

	response, err := r.cli.RawRequest(ctx, req, resp)
	return resp.Data, response, err
}

// MockAPaaSGetAPaaSWorkspaceEnumGet mock APaaSGetAPaaSWorkspaceEnumGet method
func (r *Mock) MockAPaaSGetAPaaSWorkspaceEnumGet(f func(ctx context.Context, request *GetAPaaSWorkspaceEnumGetReq, options ...MethodOptionFunc) (*GetAPaaSWorkspaceEnumGetResp, *Response, error)) {
	r.mockAPaaSGetAPaaSWorkspaceEnumGet = f
}

// UnMockAPaaSGetAPaaSWorkspaceEnumGet un-mock APaaSGetAPaaSWorkspaceEnumGet method
func (r *Mock) UnMockAPaaSGetAPaaSWorkspaceEnumGet() {
	r.mockAPaaSGetAPaaSWorkspaceEnumGet = nil
}

// GetAPaaSWorkspaceEnumGetReq ...
type GetAPaaSWorkspaceEnumGetReq struct {
	WorkspaceID string `path:"workspace_id" json:"-"` // 工作空间id, 可以从数据平台的 URL 中获取, 如 https://apaas.feishu.cn/suda/workspace/workspace_aadimx5uzpsls/table-manage/main?tableId=table_1846786627963081&tab=objectManage 中的 workspace_aadimx5uzpsls 就是 workspace_id示例值: "workspace_aadimx5uzpsls"
	EnumName    string `path:"enum_name" json:"-"`    // 枚举名称示例值: "enum_demo_1"
}

// GetAPaaSWorkspaceEnumGetResp ...
type GetAPaaSWorkspaceEnumGetResp struct {
	Name        string                                 `json:"name,omitempty"`        // 枚举名称
	Description string                                 `json:"description,omitempty"` // 枚举描述
	Options     []string                               `json:"options,omitempty"`     // 枚举值列表
	CreatedAt   string                                 `json:"created_at,omitempty"`  // 创建时间, 毫秒时间戳
	CreatedBy   *GetAPaaSWorkspaceEnumGetRespCreatedBy `json:"created_by,omitempty"`  // 创建人
}

// GetAPaaSWorkspaceEnumGetRespCreatedBy ...
type GetAPaaSWorkspaceEnumGetRespCreatedBy struct {
	ID     string `json:"id,omitempty"`     // 用户 id, 如 1693861178143800
	Name   string `json:"name,omitempty"`   // 用户姓名, 如王小小
	Avatar string `json:"avatar,omitempty"` // 用户头像 URL
}

// getAPaaSWorkspaceEnumGetResp ...
type getAPaaSWorkspaceEnumGetResp struct {
	Code  int64                         `json:"code,omitempty"` // 错误码, 非 0 表示失败
	Msg   string                        `json:"msg,omitempty"`  // 错误描述
	Data  *GetAPaaSWorkspaceEnumGetResp `json:"data,omitempty"`
	Error *ErrorDetail                  `json:"error,omitempty"`
}
