// Code generated by lark_sdk_gen. DO NOT EDIT.
/**
 * Copyright 2022 chyroc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package lark

import (
	"context"
)

// DeleteUser 调用该接口从通讯录内删除一个指定用户（该动作可以理解为员工离职）, 删除时可通过请求参数将用户所有的群组、文档、日程和应用等数据转让至他人。
//
// ## 注意事项
// - 调用该接口的应用的[通讯录权限范围](https://open.feishu.cn/document/ukTMukTMukTM/uETNz4SM1MjLxUzM/v3/guides/scope_authority)必须包含用户所属的部门。例如, 待删除用户归属部门 A、部门 B, 则应用的通讯录权限范围必须包括部门 A 和部门 B, 这样才可以成功删除用户。
// - 删除用户后, 你可以调用[获取单个用户信息](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/contact-v3/user/get)接口, 通过用户 ID 查询用户的状态（响应参数 status）, 从而确保用户已成功删除（对应已离职状态）。
//
// doc: https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/contact-v3/user/delete
// new doc: https://open.feishu.cn/document/server-docs/contact-v3/user/delete
func (r *ContactService) DeleteUser(ctx context.Context, request *DeleteUserReq, options ...MethodOptionFunc) (*DeleteUserResp, *Response, error) {
	if r.cli.mock.mockContactDeleteUser != nil {
		r.cli.Log(ctx, LogLevelDebug, "[lark] Contact#DeleteUser mock enable")
		return r.cli.mock.mockContactDeleteUser(ctx, request, options...)
	}

	req := &RawRequestReq{
		Scope:                 "Contact",
		API:                   "DeleteUser",
		Method:                "DELETE",
		URL:                   r.cli.openBaseURL + "/open-apis/contact/v3/users/:user_id",
		Body:                  request,
		MethodOption:          newMethodOption(options),
		NeedTenantAccessToken: true,
	}
	resp := new(deleteUserResp)

	response, err := r.cli.RawRequest(ctx, req, resp)
	return resp.Data, response, err
}

// MockContactDeleteUser mock ContactDeleteUser method
func (r *Mock) MockContactDeleteUser(f func(ctx context.Context, request *DeleteUserReq, options ...MethodOptionFunc) (*DeleteUserResp, *Response, error)) {
	r.mockContactDeleteUser = f
}

// UnMockContactDeleteUser un-mock ContactDeleteUser method
func (r *Mock) UnMockContactDeleteUser() {
	r.mockContactDeleteUser = nil
}

// DeleteUserReq ...
type DeleteUserReq struct {
	UserID                       string                      `path:"user_id" json:"-"`                           // 用户 ID。ID 类型需要与查询参数中的 user_id_type 类型保持一致。用户 ID 获取方式可参见[如何获取不同的用户 ID](https://open.feishu.cn/document/home/user-identity-introduction/open-id)。示例值: "ou_7dab8a3d3cdcc9da365777c7ad535d62"
	UserIDType                   *IDType                     `query:"user_id_type" json:"-"`                     // 用户 ID 类型示例值: open_id可选值有: 标识一个用户在某个应用中的身份。同一个用户在不同应用中的 Open ID 不同。[了解更多: 如何获取 Open ID](https://open.feishu.cn/document/uAjLw4CM/ugTN1YjL4UTN24CO1UjN/trouble-shooting/how-to-obtain-openid)标识一个用户在某个应用开发商下的身份。同一用户在同一开发商下的应用中的 Union ID 是相同的, 在不同开发商下的应用中的 Union ID 是不同的。通过 Union ID, 应用开发商可以把同个用户在多个应用中的身份关联起来。[了解更多: 如何获取 Union ID？](https://open.feishu.cn/document/uAjLw4CM/ugTN1YjL4UTN24CO1UjN/trouble-shooting/how-to-obtain-union-id)标识一个用户在某个租户内的身份。同一个用户在租户 A 和租户 B 内的 User ID 是不同的。在同一个租户内, 一个用户的 User ID 在所有应用（包括商店应用）中都保持一致。User ID 主要用于在不同的应用间打通用户数据。[了解更多: 如何获取 User ID？](https://open.feishu.cn/document/uAjLw4CM/ugTN1YjL4UTN24CO1UjN/trouble-shooting/how-to-obtain-user-id)默认值: `open_id`当值为 `user_id`, 字段权限要求: 获取用户 user ID
	DepartmentChatAcceptorUserID *string                     `json:"department_chat_acceptor_user_id,omitempty"` // 部门群接收者的用户 ID。被删除用户为部门群群主时, 转让群主给指定接收者。注意: ID 类型需要与查询参数中的 user_id_type 类型保持一致。用户 ID 获取方式可参见[如何获取不同的用户 ID](https://open.feishu.cn/document/home/user-identity-introduction/open-id)。- 不指定该参数时, 如果被删除用户是部门群群主, 则群主会默认转让给群内第一个入群的人。示例值: "ou_7dab8a3d3cdcc9da365777c7ad535d62"
	ExternalChatAcceptorUserID   *string                     `json:"external_chat_acceptor_user_id,omitempty"`   // 外部群接收者的用户 ID。被删除用户为外部群群主时, 转让群主给指定接收者。注意: ID 类型需要与查询参数中的 user_id_type 类型保持一致。用户 ID 获取方式可参见[如何获取不同的用户 ID](https://open.feishu.cn/document/home/user-identity-introduction/open-id)。- 不指定该参数时, 如果被删除用户是外部群群主, 则群主会默认转让给群内与被删除用户在同一组织的第一个入群的人。如果组织内只有被删除用户在群里, 则解散外部群。示例值: "ou_7dab8a3d3cdcc9da365777c7ad535d62"
	DocsAcceptorUserID           *string                     `json:"docs_acceptor_user_id,omitempty"`            // 文档接收者的用户 ID。用户被删除时, 其拥有的文档转让给接收者。注意: ID 类型需要与查询参数中的 user_id_type 类型保持一致。用户 ID 获取方式可参见[如何获取不同的用户 ID](https://open.feishu.cn/document/home/user-identity-introduction/open-id)。- 不指定接收者则默认转让给被删除用户的直属上级。如果被删除用户无直属上级, 则将文档资源保留在该用户名下。- 文档转让后, 只改变文档所有者, 其他权限不受影响。示例值: "ou_7dab8a3d3cdcc9da365777c7ad535d62"
	CalendarAcceptorUserID       *string                     `json:"calendar_acceptor_user_id,omitempty"`        // 日程接收者的用户 ID。用户被删除时, 其拥有的日程转让给接收者。注意: ID 类型需要与查询参数中的 user_id_type 类型保持一致。用户 ID 获取方式可参见[如何获取不同的用户 ID](https://open.feishu.cn/document/home/user-identity-introduction/open-id)。- 不指定接收者则默认转让给被删除用户的直属上级。如果被删除用户无直属上级, 则直接删除日程资源。示例值: "ou_7dab8a3d3cdcc9da365777c7ad535d62"
	ApplicationAcceptorUserID    *string                     `json:"application_acceptor_user_id,omitempty"`     // 应用接受者的用户 ID。用户被删除时, 其创建的应用转让给接收者。注意: ID 类型需要与查询参数中的 user_id_type 类型保持一致。用户 ID 获取方式可参见[如何获取不同的用户 ID](https://open.feishu.cn/document/home/user-identity-introduction/open-id)。- 不指定接收者则默认转让给被删除用户的直属上级。如果被删除用户无直属上级, 则保留应用在该用户名下, 但该用户无法登录开发者后台进行应用管理。企业管理员可以在管理后台手动转移应用给其他人。示例值: "ou_7dab8a3d3cdcc9da365777c7ad535d62"
	MinutesAcceptorUserID        *string                     `json:"minutes_acceptor_user_id,omitempty"`         // 妙记接收者的用户 ID。用户被删除时, 其拥有的妙记资源转让给接收者。注意: ID 类型需要与查询参数中的 user_id_type 类型保持一致。用户 ID 获取方式可参见[如何获取不同的用户 ID](https://open.feishu.cn/document/home/user-identity-introduction/open-id)。- 如果不指定接收者, 则默认转让给被删除用户的直属上级。如果被删除用户无直属上级, 则将妙记保留在该用户名下。- 妙记转让后, 只改变妙记所有者, 不影响已分享的妙记链接。示例值: "ou_7dab8a3d3cdcc9da365777c7ad535d62"
	SurveyAcceptorUserID         *string                     `json:"survey_acceptor_user_id,omitempty"`          // 飞书问卷接收者的用户 ID。用户被删除时, 其拥有的飞书问卷资源转让给接收者。注意: ID 类型需要与查询参数中的 user_id_type 类型保持一致。用户 ID 获取方式可参见[如何获取不同的用户 ID](https://open.feishu.cn/document/home/user-identity-introduction/open-id)。- 不指定接收者则默认转让给被删除用户的直属上级。如果被删除用户无直属上级, 则直接删除飞书问卷资源。示例值: "ou_7dab8a3d3cdcc9da365777c7ad535d62"
	EmailAcceptor                *DeleteUserReqEmailAcceptor `json:"email_acceptor,omitempty"`                   // 用户邮件资源的处理方式。该参数为可选参数, 如果未传值, 则默认将邮件资源转让给被删除用户的直属上级。如果被删除用户无直属上级, 则保留邮件资源在该用户名下。
	AnycrossAcceptorUserID       *string                     `json:"anycross_acceptor_user_id,omitempty"`        // 用户集成平台资源的接收者的用户 ID。注意: ID 类型需要与查询参数中的 user_id_type 类型保持一致。用户 ID 获取方式可参见[如何获取不同的用户 ID](https://open.feishu.cn/document/home/user-identity-introduction/open-id)。- 不指定接收者则默认转让给被删除用户的直属上级。如果被删除用户无直属上级, 则保留应用在该用户名下, 但该用户无法登录飞书集成平台。企业管理员可以在管理后台手动转移应用给其他人。示例值: "ou_7dab8a3d3cdcc9da365777c7ad535d62"
}

// DeleteUserReqEmailAcceptor ...
type DeleteUserReqEmailAcceptor struct {
	ProcessingType string  `json:"processing_type,omitempty"`  // 处理方式。示例值: "1"可选值有: 转移资源保留资源删除资源
	AcceptorUserID *string `json:"acceptor_user_id,omitempty"` // 邮件资源接收者的用户 ID。ID 类型需要与查询参数中的 user_id_type 类型保持一致。用户 ID 获取方式可参见[如何获取不同的用户 ID](https://open.feishu.cn/document/home/user-identity-introduction/open-id)。说明: 仅当 `processing_type` 取值为 `1` 时, 需要设置该参数值。示例值: "ou_7dab8a3d3cdcc9da365777c7ad535d62"
}

// DeleteUserResp ...
type DeleteUserResp struct{}

// deleteUserResp ...
type deleteUserResp struct {
	Code  int64           `json:"code,omitempty"` // 错误码, 非 0 表示失败
	Msg   string          `json:"msg,omitempty"`  // 错误描述
	Data  *DeleteUserResp `json:"data,omitempty"`
	Error *ErrorDetail    `json:"error,omitempty"`
}
