// Code generated by lark_sdk_gen. DO NOT EDIT.
/**
 * Copyright 2022 chyroc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package lark

import (
	"context"
)

// MergeForwardMessage 将来自同一个会话内的多条消息, 合并转发给指定的用户、群聊或话题。
//
// ## 前提条件
// - 应用需要开启[机器人能力](https://open.feishu.cn/document/uAjLw4CM/ugTN1YjL4UTN24CO1UjN/trouble-shooting/how-to-enable-bot-ability)
// - 向用户合并转发消息时, 用户需要在机器人的[可用范围](https://open.feishu.cn/document/home/introduction-to-scope-and-authorization/availability)内。
// - 向群组合并转发消息, 机器人需要在该群组中, 且拥有发言权限。
// - 合并转发生成的新消息的消息内容为固定值[Merged and Forwarded Message], 其中的子消息可以使用[获取指定消息的内容](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message/get)接口获取。
// ## 使用限制
// - 不支持合并转发[系统消息（system）](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/im-v1/message/create_json#e159cb73)。
// - 不支持合并转发来自不同群聊的消息。
// - 不支持同时合并转发来自多个话题中的消息。
// - 不支持同时合并转发普通消息与话题中的消息。
// - 不支持再次合并转发 合并转发消息中的子消息（含有[upper_message_id]字段的消息）。
// - 为避免消息发送频繁对用户造成打扰, 向同一用户发送消息的限频为 [5 QPS]、向同一群组发送消息的限频为群内机器人共享 [5 QPS]。
//
// doc: https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message/merge_forward
// new doc: https://open.feishu.cn/document/server-docs/im-v1/message/merge_forward
func (r *MessageService) MergeForwardMessage(ctx context.Context, request *MergeForwardMessageReq, options ...MethodOptionFunc) (*MergeForwardMessageResp, *Response, error) {
	if r.cli.mock.mockMessageMergeForwardMessage != nil {
		r.cli.Log(ctx, LogLevelDebug, "[lark] Message#MergeForwardMessage mock enable")
		return r.cli.mock.mockMessageMergeForwardMessage(ctx, request, options...)
	}

	req := &RawRequestReq{
		Scope:                 "Message",
		API:                   "MergeForwardMessage",
		Method:                "POST",
		URL:                   r.cli.openBaseURL + "/open-apis/im/v1/messages/merge_forward",
		Body:                  request,
		MethodOption:          newMethodOption(options),
		NeedTenantAccessToken: true,
	}
	resp := new(mergeForwardMessageResp)

	response, err := r.cli.RawRequest(ctx, req, resp)
	return resp.Data, response, err
}

// MockMessageMergeForwardMessage mock MessageMergeForwardMessage method
func (r *Mock) MockMessageMergeForwardMessage(f func(ctx context.Context, request *MergeForwardMessageReq, options ...MethodOptionFunc) (*MergeForwardMessageResp, *Response, error)) {
	r.mockMessageMergeForwardMessage = f
}

// UnMockMessageMergeForwardMessage un-mock MessageMergeForwardMessage method
func (r *Mock) UnMockMessageMergeForwardMessage() {
	r.mockMessageMergeForwardMessage = nil
}

// MergeForwardMessageReq ...
type MergeForwardMessageReq struct {
	ReceiveIDType IDType   `query:"receive_id_type" json:"-"` // 消息接收者 ID 类型。示例值: open_id可选值有: 标识一个用户在某个应用中的身份。同一个用户在不同应用中的 Open ID 不同。[了解更多: 如何获取 Open ID](https://open.feishu.cn/document/uAjLw4CM/ugTN1YjL4UTN24CO1UjN/trouble-shooting/how-to-obtain-openid)标识一个用户在某个租户内的身份。同一个用户在租户 A 和租户 B 内的 User ID 是不同的。在同一个租户内, 一个用户的 User ID 在所有应用（包括商店应用）中都保持一致。User ID 主要用于在不同的应用间打通用户数据。[了解更多: 如何获取 User ID？](https://open.feishu.cn/document/uAjLw4CM/ugTN1YjL4UTN24CO1UjN/trouble-shooting/how-to-obtain-user-id)标识一个用户在某个应用开发商下的身份。同一用户在同一开发商下的应用中的 Union ID 是相同的, 在不同开发商下的应用中的 Union ID 是不同的。通过 Union ID, 应用开发商可以把同个用户在多个应用中的身份关联起来。[了解更多: 如何获取 Union ID？](https://open.feishu.cn/document/uAjLw4CM/ugTN1YjL4UTN24CO1UjN/trouble-shooting/how-to-obtain-union-id)以用户的真实邮箱来标识用户。以群 ID 来标识群聊。[了解更多: 如何获取群 ID ](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/chat-id-description)以话题 ID 来标识话题。了解更多: [话题介绍](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message/thread-introduction)当值为 `user_id`, 字段权限要求: 获取用户 user ID
	UUID          *string  `query:"uuid" json:"-"`            // 自定义设置的唯一字符串序列, 用于在合并转发消息时请求去重。持有相同 uuid 的请求, 在 1 小时内向同一目标的合并转发只可成功一次。示例值: b13g2t38-1jd2-458b-8djf-dtbca5104204 最大长度: `50` 字符
	ReceiveID     string   `json:"receive_id,omitempty"`      // 消息接收者 ID, ID 类型与 `receive_id_type` 的值一致。示例值: "oc_a0553eda9014c201e6969b478895c230"
	MessageIDList []string `json:"message_id_list,omitempty"` // 待转发的消息 ID 列表, 列表内的消息必须来自同一个会话。ID 获取方式: - 调用[发送消息](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message/create)接口后, 从响应结果的 `message_id` 参数获取。- 监听[接收消息](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message/events/receive)事件, 当触发该事件后可以从事件体内获取消息的 `message_id`。- 调用[获取会话历史消息](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message/list)接口, 从响应结果的 `message_id` 参数获取。示例值: ["om_dc13264520392913993dd051dba21dcf"] 长度范围: `1` ～ `100`
}

// MergeForwardMessageResp ...
type MergeForwardMessageResp struct {
	Message              *MergeForwardMessageRespMessage `json:"message,omitempty"`                 // 合并转发生成的新消息。
	InvalidMessageIDList []string                        `json:"invalid_message_id_list,omitempty"` // 无效的消息 ID 列表, 如不存在的消息、已被撤回的消息、当前操作者不可见的历史消息、接口不支持的消息类型等。
}

// MergeForwardMessageRespMessage ...
type MergeForwardMessageRespMessage struct {
	MessageID      string       `json:"message_id,omitempty"`       // 消息 ID。合并转发后由系统自动生成的消息唯一标识。后续对消息的管理维护操作均需要使用该 ID。
	RootID         string       `json:"root_id,omitempty"`          // 根消息 ID, 仅在回复消息场景会有返回值。了解 root_id 可参见[消息管理概述](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message/intro)。
	ParentID       string       `json:"parent_id,omitempty"`        // 父消息 ID, 仅在回复消息场景会有返回值。了解 parent_id 可参见[消息管理概述](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message/intro)。
	ThreadID       string       `json:"thread_id,omitempty"`        // 消息所属的话题 ID（不返回说明该消息非话题消息）, 了解话题可参见[话题概述](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message/thread-introduction)。
	MsgType        MsgType      `json:"msg_type,omitempty"`         // 消息类型, 取值 merge_forward 表示合并转发消息。了解消息类型定义, 参考[接收消息内容](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/im-v1/message/events/message_content)。
	CreateTime     string       `json:"create_time,omitempty"`      // 消息生成的时间戳。单位: 毫秒
	UpdateTime     string       `json:"update_time,omitempty"`      // 消息更新的时间戳。单位: 毫秒
	Deleted        bool         `json:"deleted,omitempty"`          // 消息是否被撤回。返回 false 表示未被撤回。
	Updated        bool         `json:"updated,omitempty"`          // 消息是否被更新。返回 false 表示未被更新。
	ChatID         string       `json:"chat_id,omitempty"`          // 消息所属的群 ID。你可以调用[获取群信息](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/chat/get)接口, 根据群 ID 获取群详情。
	Sender         *Sender      `json:"sender,omitempty"`           // 消息的发送者信息。
	Body           *MessageBody `json:"body,omitempty"`             // 通过 `body` 内的 `content` 参数, 返回所发送的消息内容。
	Mentions       []*Mention   `json:"mentions,omitempty"`         // 发送的消息内, 被 @ 的用户或机器人列表。
	UpperMessageID string       `json:"upper_message_id,omitempty"` // 合并转发消息中, 上一层级的消息 ID。了解 upper_message_id 可参见[消息管理概述](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message/intro)。
}

// MergeForwardMessageRespMessageBody ...
type MergeForwardMessageRespMessageBody struct {
	Content string `json:"content,omitempty"` // 消息内容, JSON 结构序列化后的字符串, 合并转发生成的新消息的消息内容为固定值[Merged and Forwarded Message], 其中的子消息可以使用[获取指定消息的内容](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message/get)接口获取。
}

// MergeForwardMessageRespMessageMention ...
type MergeForwardMessageRespMessageMention struct {
	Key       string `json:"key,omitempty"`        // 被 @ 的用户或机器人序号。例如, 第 3 个被 @ 到的成员, 取值为 `@_user_3`。
	ID        string `json:"id,omitempty"`         // 被 @ 的用户或者机器人的 open_id。
	IDType    IDType `json:"id_type,omitempty"`    // 被 @ 的用户或机器人 ID 类型, 目前仅支持 `open_id` ([什么是 Open ID](https://open.feishu.cn/document/home/user-identity-introduction/open-id))。
	Name      string `json:"name,omitempty"`       // 被 @ 的用户或机器人的姓名。
	TenantKey string `json:"tenant_key,omitempty"` // 租户唯一标识。该标识用来识别被 @ 用户或机器人的租户, 也可以用来获取租户访问凭证（tenant_access_token）。
}

// MergeForwardMessageRespMessageSender ...
type MergeForwardMessageRespMessageSender struct {
	ID         string `json:"id,omitempty"`          // 发送者的 ID。
	IDType     IDType `json:"id_type,omitempty"`     // 发送者的 ID 类型。可能值有: `open_id`: 表示发送者为用户, 且返回的 ID 是用户的 open_id。- `app_id`: 表示发送者为应用, 切返回的 ID 是应用的 app_id。
	SenderType string `json:"sender_type,omitempty"` // 发送者类型。可能值有: `user`: 用户- `app`: 应用- `anonymous`: 匿名- `unknown`: 未知
	TenantKey  string `json:"tenant_key,omitempty"`  // 租户唯一标识。该标识用来识别租户, 也可以用来获取租户访问凭证（tenant_access_token）。
}

// mergeForwardMessageResp ...
type mergeForwardMessageResp struct {
	Code  int64                    `json:"code,omitempty"` // 错误码, 非 0 表示失败
	Msg   string                   `json:"msg,omitempty"`  // 错误描述
	Data  *MergeForwardMessageResp `json:"data,omitempty"`
	Error *ErrorDetail             `json:"error,omitempty"`
}
