// Code generated by lark_sdk_gen. DO NOT EDIT.
/**
 * Copyright 2022 chyroc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package lark

import (
	"context"
)

// BatchUpdateSheet 根据电子表格的 token 对工作表进行操作, 包括增加工作表、复制工作表、删除工作表。
//
// ::: note
// 该接口和 [更新工作表属性](https://open.feishu.cn/document/ukTMukTMukTM/ugjMzUjL4IzM14COyMTN) 的请求地址相同, 但参数不同, 调用前请仔细阅读文档。
//
// doc: https://open.feishu.cn/document/ukTMukTMukTM/uYTMzUjL2EzM14iNxMTN
// new doc: https://open.feishu.cn/document/server-docs/docs/sheets-v3/spreadsheet-sheet/operate-sheets
func (r *DriveService) BatchUpdateSheet(ctx context.Context, request *BatchUpdateSheetReq, options ...MethodOptionFunc) (*BatchUpdateSheetResp, *Response, error) {
	if r.cli.mock.mockDriveBatchUpdateSheet != nil {
		r.cli.Log(ctx, LogLevelDebug, "[lark] Drive#BatchUpdateSheet mock enable")
		return r.cli.mock.mockDriveBatchUpdateSheet(ctx, request, options...)
	}

	req := &RawRequestReq{
		Scope:                 "Drive",
		API:                   "BatchUpdateSheet",
		Method:                "POST",
		URL:                   r.cli.openBaseURL + "/open-apis/sheets/v2/spreadsheets/:spreadsheet_token/sheets_batch_update",
		Body:                  request,
		MethodOption:          newMethodOption(options),
		NeedTenantAccessToken: true,
		NeedUserAccessToken:   true,
	}
	resp := new(batchUpdateSheetResp)

	response, err := r.cli.RawRequest(ctx, req, resp)
	return resp.Data, response, err
}

// MockDriveBatchUpdateSheet mock DriveBatchUpdateSheet method
func (r *Mock) MockDriveBatchUpdateSheet(f func(ctx context.Context, request *BatchUpdateSheetReq, options ...MethodOptionFunc) (*BatchUpdateSheetResp, *Response, error)) {
	r.mockDriveBatchUpdateSheet = f
}

// UnMockDriveBatchUpdateSheet un-mock DriveBatchUpdateSheet method
func (r *Mock) UnMockDriveBatchUpdateSheet() {
	r.mockDriveBatchUpdateSheet = nil
}

// BatchUpdateSheetReq ...
type BatchUpdateSheetReq struct {
	SpreadSheetToken string                        `path:"spreadsheet_token" json:"-"` // 电子表格的 token。可通过以下两种方式获取。了解更多, 参考[电子表格概述](https://open.feishu.cn/document/ukTMukTMukTM/uATMzUjLwEzM14CMxMTN/overview)。-  电子表格的 URL: https://sample.feishu.cn/sheets/[Ios7sNNEphp3WbtnbCscPqabcef]- 调用[获取文件夹中的文件清单](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/drive-v1/file/list)
	Requests         []*BatchUpdateSheetReqRequest `json:"requests,omitempty"`         // 支持增加、复制、和删除工作表。一次请求可以同时进行多个操作。
}

// BatchUpdateSheetReqRequest ...
type BatchUpdateSheetReqRequest struct {
	UpdateSheet *BatchUpdateSheetReqRequestUpdateSheet `json:"updateSheet,omitempty"` // 更新工作表
	AddSheet    *BatchUpdateSheetReqRequestAddSheet    `json:"addSheet,omitempty"`    // 增加工作表。
	CopySheet   *BatchUpdateSheetReqRequestCopySheet   `json:"copySheet,omitempty"`   // 复制工作表。复制的新工作表位于源工作表索引位置之后。
	DeleteSheet *BatchUpdateSheetReqRequestDeleteSheet `json:"deleteSheet,omitempty"` // 删除工作表。
}

// BatchUpdateSheetReqRequestAddSheet ...
type BatchUpdateSheetReqRequestAddSheet struct {
	Properties *BatchUpdateSheetReqRequestAddSheetProperties `json:"properties,omitempty"` // 工作表属性
}

// BatchUpdateSheetReqRequestAddSheetProperties ...
type BatchUpdateSheetReqRequestAddSheetProperties struct {
	Title string `json:"title,omitempty"` // 新增工作表的标题
	Index *int64 `json:"index,omitempty"` // 新增工作表的位置。不填默认在工作表的第 0 索引位置增加工作表。
}

// BatchUpdateSheetReqRequestCopySheet ...
type BatchUpdateSheetReqRequestCopySheet struct {
	Source      *BatchUpdateSheetReqRequestCopySheetSource      `json:"source,omitempty"`      // 需要复制的工作表资源
	Destination *BatchUpdateSheetReqRequestCopySheetDestination `json:"destination,omitempty"` // 新工作表的属性
}

// BatchUpdateSheetReqRequestCopySheetDestination ...
type BatchUpdateSheetReqRequestCopySheetDestination struct {
	Title *string `json:"title,omitempty"` // 新工作表名称。不填默认为“源工作表名称”+“(副本_源工作表的 `index` 值)”, 如 “Sheet1(副本_0)”。
}

// BatchUpdateSheetReqRequestCopySheetSource ...
type BatchUpdateSheetReqRequestCopySheetSource struct {
	SheetID string `json:"sheetId,omitempty"` // 源工作表的 ID。调用[获取工作表](https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet-sheet/query)获取 ID。
}

// BatchUpdateSheetReqRequestDeleteSheet ...
type BatchUpdateSheetReqRequestDeleteSheet struct {
	SheetID string `json:"sheetId,omitempty"` // 要删除的工作表的 ID。调用[获取工作表](https://open.feishu.cn/document/ukTMukTMukTM/uUDN04SN0QjL1QDN/sheets-v3/spreadsheet-sheet/query)获取 ID。
}

// BatchUpdateSheetReqRequestUpdateSheet ...
type BatchUpdateSheetReqRequestUpdateSheet struct {
	Properties *BatchUpdateSheetReqRequestUpdateSheetProperties `json:"properties,omitempty"` // 工作表属性
}

// BatchUpdateSheetReqRequestUpdateSheetProperties ...
type BatchUpdateSheetReqRequestUpdateSheetProperties struct {
	SheetID        string                                                  `json:"sheetId,omitempty"`        // read-only ,作为表格唯一识别参数
	Title          *string                                                 `json:"title,omitempty"`          // 更改工作表标题
	Index          *int64                                                  `json:"index,omitempty"`          // 移动工作表的位置
	Hidden         *bool                                                   `json:"hidden,omitempty"`         // 隐藏表格，默认 false
	FrozenRowCount *int64                                                  `json:"frozenRowCount,omitempty"` // 冻结行数，小于等于工作表的最大行数，0表示取消冻结行
	FrozenColCount *int64                                                  `json:"frozenColCount,omitempty"` // 该 sheet 的冻结列数，小于等于工作表的最大列数，0表示取消冻结列
	Protect        *BatchUpdateSheetReqRequestUpdateSheetPropertiesProtect `json:"protect,omitempty"`        // 锁定表格
}

// BatchUpdateSheetReqRequestUpdateSheetPropertiesProtect ...
type BatchUpdateSheetReqRequestUpdateSheetPropertiesProtect struct {
	Lock     string   `json:"lock,omitempty"`     // LOCK 、UNLOCK 上锁/解锁
	LockInfo *string  `json:"lockInfo,omitempty"` // 锁定信息
	UserIDs  []string `json:"userIDs,omitempty"`  // 除了本人与所有者外，添加其他的可编辑人员,user_id_type不为空时使用该字段
}

// BatchUpdateSheetResp ...
type BatchUpdateSheetResp struct {
	Replies []*BatchUpdateSheetRespReply `json:"replies,omitempty"` // 本次操作工作表的结果
}

// BatchUpdateSheetRespReply ...
type BatchUpdateSheetRespReply struct {
	UpdateSheet *BatchUpdateSheetRespReplyUpdateSheet `json:"updateSheet,omitempty"` // 更新工作表
	AddSheet    *BatchUpdateSheetRespReplyAddSheet    `json:"addSheet,omitempty"`    // 增加工作表的结果
	CopySheet   *BatchUpdateSheetRespReplyCopySheet   `json:"copySheet,omitempty"`   // 复制工作表的结果
	DeleteSheet *BatchUpdateSheetRespReplyDeleteSheet `json:"deleteSheet,omitempty"` // 删除工作表的结果
}

// BatchUpdateSheetRespReplyAddSheet ...
type BatchUpdateSheetRespReplyAddSheet struct {
	Properties *BatchUpdateSheetRespReplyAddSheetProperties `json:"properties,omitempty"` // 新增工作表的属性
}

// BatchUpdateSheetRespReplyAddSheetProperties ...
type BatchUpdateSheetRespReplyAddSheetProperties struct {
	SheetID string `json:"sheetId,omitempty"` // 新增工作表的 `sheetId`
	Title   string `json:"title,omitempty"`   // 新增工作表的标题
	Index   int64  `json:"index,omitempty"`   // 新增工作表的位置
}

// BatchUpdateSheetRespReplyCopySheet ...
type BatchUpdateSheetRespReplyCopySheet struct {
	Properties *BatchUpdateSheetRespReplyCopySheetProperties `json:"properties,omitempty"` // 复制的工作表的属性
}

// BatchUpdateSheetRespReplyCopySheetProperties ...
type BatchUpdateSheetRespReplyCopySheetProperties struct {
	SheetID string `json:"sheetId,omitempty"` // 复制工作表的 `sheetId`
	Title   string `json:"title,omitempty"`   // 复制工作表的标题
	Index   int64  `json:"index,omitempty"`   // 复制的工作表的位置
}

// BatchUpdateSheetRespReplyDeleteSheet ...
type BatchUpdateSheetRespReplyDeleteSheet struct {
	Result  bool   `json:"result,omitempty"`  // 删除工作表是否成功
	SheetID string `json:"sheetId,omitempty"` // 被删除的工作表的 ID
}

// BatchUpdateSheetRespReplyUpdateSheet ...
type BatchUpdateSheetRespReplyUpdateSheet struct {
	Properties *BatchUpdateSheetRespReplyUpdateSheetProperties `json:"properties,omitempty"` // 工作表属性
}

// BatchUpdateSheetRespReplyUpdateSheetProperties ...
type BatchUpdateSheetRespReplyUpdateSheetProperties struct {
	SheetID        string                                                 `json:"sheetId,omitempty"`        // read-only ,作为表格唯一识别参数
	Title          string                                                 `json:"title,omitempty"`          // 更改工作表标题
	Index          int64                                                  `json:"index,omitempty"`          // 移动工作表的位置
	Hidden         bool                                                   `json:"hidden,omitempty"`         // 隐藏表格，默认 false
	FrozenRowCount int64                                                  `json:"frozenRowCount,omitempty"` // 冻结行数，小于等于工作表的最大行数，0表示取消冻结行
	FrozenColCount int64                                                  `json:"frozenColCount,omitempty"` // 该 sheet 的冻结列数，小于等于工作表的最大列数，0表示取消冻结列
	Protect        *BatchUpdateSheetRespReplyUpdateSheetPropertiesProtect `json:"protect,omitempty"`        // 锁定表格
}

// BatchUpdateSheetRespReplyUpdateSheetPropertiesProtect ...
type BatchUpdateSheetRespReplyUpdateSheetPropertiesProtect struct {
	Lock     string   `json:"lock,omitempty"`     // LOCK 、UNLOCK 上锁/解锁
	LockInfo string   `json:"lockInfo,omitempty"` // 锁定信息
	UserIDs  []string `json:"userIDs,omitempty"`  // 除了本人与所有者外，添加其他的可编辑人员,user_id_type不为空时使用该字段
}

// batchUpdateSheetResp ...
type batchUpdateSheetResp struct {
	Code int64                 `json:"code,omitempty"`
	Msg  string                `json:"msg,omitempty"`
	Data *BatchUpdateSheetResp `json:"data,omitempty"`
}
