// Code generated by lark_sdk_gen. DO NOT EDIT.
/**
 * Copyright 2022 chyroc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package lark

import (
	"context"
)

// QueryCoreHRJobFamilyMultiTimeline - 接口支持查询出对象生效时间段在指定的start_date和end_date之间的版本
//
// - 接口支持对象版本相关字段的查询和返回（默认返回id和version_id）
// - 适用于需要回顾某段时间内对象版本变化的场景
// 延迟说明: 数据库主从延迟2s以内, 即: 直接创建对象后2s内调用此接口可能查询不到数据。
//
// doc: https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/job_family/query_multi_timeline
// new doc: https://open.feishu.cn/document/corehr-v1/job-management/job_family/query_multi_timeline
func (r *CoreHRService) QueryCoreHRJobFamilyMultiTimeline(ctx context.Context, request *QueryCoreHRJobFamilyMultiTimelineReq, options ...MethodOptionFunc) (*QueryCoreHRJobFamilyMultiTimelineResp, *Response, error) {
	if r.cli.mock.mockCoreHRQueryCoreHRJobFamilyMultiTimeline != nil {
		r.cli.Log(ctx, LogLevelDebug, "[lark] CoreHR#QueryCoreHRJobFamilyMultiTimeline mock enable")
		return r.cli.mock.mockCoreHRQueryCoreHRJobFamilyMultiTimeline(ctx, request, options...)
	}

	req := &RawRequestReq{
		Scope:                 "CoreHR",
		API:                   "QueryCoreHRJobFamilyMultiTimeline",
		Method:                "POST",
		URL:                   r.cli.openBaseURL + "/open-apis/corehr/v2/job_families/query_multi_timeline",
		Body:                  request,
		MethodOption:          newMethodOption(options),
		NeedTenantAccessToken: true,
	}
	resp := new(queryCoreHRJobFamilyMultiTimelineResp)

	response, err := r.cli.RawRequest(ctx, req, resp)
	return resp.Data, response, err
}

// MockCoreHRQueryCoreHRJobFamilyMultiTimeline mock CoreHRQueryCoreHRJobFamilyMultiTimeline method
func (r *Mock) MockCoreHRQueryCoreHRJobFamilyMultiTimeline(f func(ctx context.Context, request *QueryCoreHRJobFamilyMultiTimelineReq, options ...MethodOptionFunc) (*QueryCoreHRJobFamilyMultiTimelineResp, *Response, error)) {
	r.mockCoreHRQueryCoreHRJobFamilyMultiTimeline = f
}

// UnMockCoreHRQueryCoreHRJobFamilyMultiTimeline un-mock CoreHRQueryCoreHRJobFamilyMultiTimeline method
func (r *Mock) UnMockCoreHRQueryCoreHRJobFamilyMultiTimeline() {
	r.mockCoreHRQueryCoreHRJobFamilyMultiTimeline = nil
}

// QueryCoreHRJobFamilyMultiTimelineReq ...
type QueryCoreHRJobFamilyMultiTimelineReq struct {
	JobFamilyIDs []string `json:"job_family_ids,omitempty"` // 序列ID。ID获取方式: 调用[【新建序列】](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/job_family/create)[【查询租户的序列信息】](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/job_family/list)等接口可以返回序列ID示例值: ["7094136522860922111"] 长度范围: `1` ～ `10`
	StartDate    *string  `json:"start_date,omitempty"`     // 查询开始时间（包含）- start_date 不能大于 end_date- 必填字段, 无默认值示例值: "2024-01-01" 长度范围: `10` ～ `10` 字符- 正则校验: `^((([0-9]{3}[1-9]|[0-9]{2}[1-9][0-9]{1}|[0-9]{1}[1-9][0-9]{2}|[1-9][0-9]{3})-(((0[13578]|1[02])-(0[1-9]|[12][0-9]|3[01]))|((0[469]|11)-(0[1-9]|[12][0-9]|30))|(02-(0[1-9]|[1][0-9]|2[0-8]))))|((([0-9]{2})(0[48]|[2468][048]|[13579][26])|((0[48]|[2468][048]|[3579][26])00))-02-29))$`
	EndDate      *string  `json:"end_date,omitempty"`       // 查询结束时间(不包含)- 必填字段, 无默认值示例值: "2024-12-31" 长度范围: `10` ～ `10` 字符- 正则校验: `^((([0-9]{3}[1-9]|[0-9]{2}[1-9][0-9]{1}|[0-9]{1}[1-9][0-9]{2}|[1-9][0-9]{3})-(((0[13578]|1[02])-(0[1-9]|[12][0-9]|3[01]))|((0[469]|11)-(0[1-9]|[12][0-9]|30))|(02-(0[1-9]|[1][0-9]|2[0-8]))))|((([0-9]{2})(0[48]|[2468][048]|[13579][26])|((0[48]|[2468][048]|[3579][26])00))-02-29))$`
	Fields       []string `json:"fields,omitempty"`         // 返回数据的字段列表, 可选["job_family_name", "code", "active", "parent_job_family", "selectable", "pathway", "description", "effective_date", "expiration_date"]- 无默认值, 为空时只能查询到ID示例值: ["job_family_name"] 长度范围: `0` ～ `100`
}

// QueryCoreHRJobFamilyMultiTimelineResp ...
type QueryCoreHRJobFamilyMultiTimelineResp struct {
	Items []*QueryCoreHRJobFamilyMultiTimelineRespItem `json:"items,omitempty"` // 序列信息
}

// QueryCoreHRJobFamilyMultiTimelineRespItem ...
type QueryCoreHRJobFamilyMultiTimelineRespItem struct {
	JobFamilyVersionData []*QueryCoreHRJobFamilyMultiTimelineRespItemJobFamilyVersionData `json:"job_family_version_data,omitempty"` // 序列版本信息
}

// QueryCoreHRJobFamilyMultiTimelineRespItemJobFamilyVersionData ...
type QueryCoreHRJobFamilyMultiTimelineRespItemJobFamilyVersionData struct {
	JobFamilyID        string                                                                        `json:"job_family_id,omitempty"`         // 序列 ID
	JobFamilyVersionID string                                                                        `json:"job_family_version_id,omitempty"` // 序列版本 ID
	JobFamilyNames     []*QueryCoreHRJobFamilyMultiTimelineRespItemJobFamilyVersionDataJobFamilyName `json:"job_family_names,omitempty"`      // 序列名称
	EffectiveDate      string                                                                        `json:"effective_date,omitempty"`        // 当前版本生效日期- 返回格式: YYYY-MM-DD （最小单位到日）- 日期范围:1900-01-01 ～9999-12-31 - 详情可以参考[时间轴介绍](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/about-timeline-version)
	ExpirationDate     string                                                                        `json:"expiration_date,omitempty"`       // 当前版本失效日期- 返回格式: YYYY-MM-DD （最小单位到日）- 日期范围:1900-01-01 ～9999-12-31 - 详情可以参考[时间轴介绍](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/about-timeline-version)
	Active             bool                                                                          `json:"active,omitempty"`                // 是否启用
	Descriptions       []*QueryCoreHRJobFamilyMultiTimelineRespItemJobFamilyVersionDataDescription   `json:"descriptions,omitempty"`          // 描述
	Selectable         bool                                                                          `json:"selectable,omitempty"`            // 是否可被使用, true为可被使用, false为不可被使用
	ParentJobFamilyID  string                                                                        `json:"parent_job_family_id,omitempty"`  // 上级序列 ID, 详细信息可通过[【查询单个序列】](/uAjLw4CM/ukTMukTMukTM/reference/corehr-v1/job_family/get)接口查询获得（若查询的是一级序列, 则该字段不展示）
	PathwayIDs         []string                                                                      `json:"pathway_ids,omitempty"`           // 通道ID, 详情可以参考[【获取通道信息】](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/corehr-v2/pathway/batch_get)
	Code               string                                                                        `json:"code,omitempty"`                  // 编码
}

// QueryCoreHRJobFamilyMultiTimelineRespItemJobFamilyVersionDataDescription ...
type QueryCoreHRJobFamilyMultiTimelineRespItemJobFamilyVersionDataDescription struct {
	Lang  string `json:"lang,omitempty"`  // 语言- 中文用zh-CN, 英文用en-US。
	Value string `json:"value,omitempty"` // 文本内容
}

// QueryCoreHRJobFamilyMultiTimelineRespItemJobFamilyVersionDataJobFamilyName ...
type QueryCoreHRJobFamilyMultiTimelineRespItemJobFamilyVersionDataJobFamilyName struct {
	Lang  string `json:"lang,omitempty"`  // 语言- 中文用zh-CN, 英文用en-US。
	Value string `json:"value,omitempty"` // 文本内容
}

// queryCoreHRJobFamilyMultiTimelineResp ...
type queryCoreHRJobFamilyMultiTimelineResp struct {
	Code  int64                                  `json:"code,omitempty"` // 错误码, 非 0 表示失败
	Msg   string                                 `json:"msg,omitempty"`  // 错误描述
	Data  *QueryCoreHRJobFamilyMultiTimelineResp `json:"data,omitempty"`
	Error *ErrorDetail                           `json:"error,omitempty"`
}
